/* eslint-disable react/prop-types */
import type { LocalizedTripProps } from "./localized-combined-trip-detail";
import TripStructuredData from "./trip-structured-data";
import styles from "./xiamen-4-days/page.module.css";

const ui = {
  "zh-CN": { eyebrow: "5 DAYS · PRIVATE FUJIAN JOURNEY", subtitle: "第一次来福建，从厦门的海走到泉州的古城。", why: "五天，刚好认识福建的几种样子。", pace: "这不是一条必须照着走的路线。", stay: "住哪里、怎么走，也可以一起安排。", included: "最终包含什么，在确认行程时说清楚。", forYou: "这条路线，比较适合这样的旅行。", final: "喜欢这条路线，就把它改成属于你的福建旅行。", contact: "免费定制这条路线 →", dayByDay: "这五天，可以这样走。", plan: "/plan?route=福建经典5日&days=5&destinations=厦门,土楼,泉州", labels: ["海边开始", "走进土楼", "认识泉州", "不用赶路"] },
  en: { eyebrow: "5 DAYS · PRIVATE FUJIAN JOURNEY", subtitle: "From Xiamen’s coast to Quanzhou’s old city.", why: "Five days to meet several sides of Fujian.", pace: "This is a framework, not a route you must follow exactly.", stay: "Stay and transport, arranged together.", included: "The final inclusions are confirmed with your itinerary.", forYou: "This journey is a good fit if…", final: "Like the route? Make it your own Fujian journey.", contact: "Customize this journey →", dayByDay: "Five days, at an easy pace.", plan: "/en/plan?route=classic-fujian-5-days&days=5&destinations=xiamen,tulou,quanzhou", labels: ["Start by the sea", "Enter the tulou valleys", "Meet Quanzhou", "Leave room to breathe"] },
  "zh-TW": { eyebrow: "5 DAYS · PRIVATE FUJIAN JOURNEY", subtitle: "第一次來福建，從廈門的海走到泉州的古城。", why: "五天，剛好認識福建的幾種樣子。", pace: "這不是一條必須照著走的路線。", stay: "住哪裡、怎麼走，也可以一起安排。", included: "最終包含什麼，在確認行程時說清楚。", forYou: "這條路線，比較適合這樣的旅行。", final: "喜歡這條路線，就把它改成屬於你的福建旅行。", contact: "免費訂製這條路線 →", dayByDay: "這五天，可以這樣走。", plan: "/zh-tw/plan?route=福建經典5日&days=5&destinations=廈門,土樓,泉州", labels: ["從海邊開始", "走進土樓", "認識泉州", "不用趕路"] },
} as const;

export default function FujianClassicRoute({ props }: { props: LocalizedTripProps }) {
  const copy = ui[props.locale];
  const isEn = props.locale === "en";
  const dayLabels = isEn ? ["Arrival in Xiamen", "Xiamen → Gulangyu", "Xiamen → Fujian Tulou", "Fujian Tulou → Quanzhou", "Quanzhou"] : props.days.map((day) => day.title);
  const trust = isEn ? ["Private car", "Flexible days", "First-time friendly", "No forced shopping"] : props.locale === "zh-TW" ? ["私人用車", "行程可調整", "適合初次到訪", "不預設購物"] : ["私人用車", "行程可调整", "适合第一次来福建", "不默认安排购物"];
  return <main className={`trip-detail-page ${styles.themePage} ${styles.classicPage}`} lang={isEn ? "en" : props.locale === "zh-TW" ? "zh-Hant" : "zh-Hans"}>
    <TripStructuredData title={props.title} description={props.intro} days={props.days} locale={props.locale} />
    <section className={styles.classicHero}><img src={props.hero} alt="" aria-hidden="true"/><div className="shell"><p>{copy.eyebrow}</p><h1>{props.title}</h1><h2>{copy.subtitle}</h2><div className={styles.classicRouteLine}>{isEn ? "Xiamen → Gulangyu → Fujian Tulou → Quanzhou" : "厦门 → 鼓浪屿 → 福建土楼 → 泉州"}</div><p className={styles.classicIntro}>{props.intro}</p><div className={styles.classicHeroActions}><a className={styles.classicPrimary} href={copy.plan}>{copy.contact}</a><a href="#day-01">{isEn ? "See the days ↓" : props.locale === "zh-TW" ? "先看看每天怎麼走 ↓" : "先看看每天怎么玩 ↓"}</a></div><ul className={styles.classicTrust}>{trust.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className={styles.classicSection}><div className="shell"><p className={styles.classicEyebrow}>WHY THIS JOURNEY</p><h2>{copy.why}</h2><div className={styles.classicFour}>{copy.labels.map((label, i) => <article key={label}><span>0{i + 1}</span><h3>{label}</h3><p>{["从厦门和鼓浪屿开始，旅行节奏轻松一些。", "离开城市，看看福建山谷、村落和土楼里的生活。", "寺庙、古城、红砖厝和闽南文化，让旅程不只有风景。", "私人用车串联城市，根据同行人的节奏调整每天安排。"][i]}</p></article>)}</div></div></section>
    <section className={styles.classicDays} id="itinerary"><div className="shell"><p className={styles.classicEyebrow}>DAY BY DAY</p><h2>{copy.dayByDay}</h2>{props.days.map((day, i) => <article className={styles.classicDay} id={`day-${day.number}`} key={day.number}><div className={styles.classicDayNo}>DAY {day.number}</div><div className={styles.classicDayText}><h3>{dayLabels[i]}</h3><p className={styles.classicLead}>{day.lead}</p><p>{day.description}</p><ul>{day.stops.map((stop) => <li key={stop.name}><b>{stop.name}</b><span>{stop.text}</span></li>)}</ul><p className={styles.classicStay}><b>{isEn ? "Stay suggestion" : props.locale === "zh-TW" ? "住宿建議" : "住宿建议"}</b>{day.details[0]?.lines.join(" · ")}</p></div><div className={styles.classicDayImage}><img src={day.images[0][0]} alt={day.images[0][1]} loading="lazy"/><img src={day.images[1]?.[0] ?? day.images[0][0]} alt={day.images[1]?.[1] ?? day.images[0][1]} loading="lazy"/></div></article>)}</div></section>
    <section className={styles.classicSection}><div className="shell"><p className={styles.classicEyebrow}>TRAVEL AT YOUR PACE</p><h2>{copy.pace}</h2><p className={styles.classicWideText}>{isEn ? "Five days is a reference framework. Reduce walking and hotel changes for parents and children, or make more room for food, photography, history, or local life." : "五天只是一个参考框架。带着父母和孩子，可以减少步行、降低换酒店频率；喜欢美食、摄影、历史或当地生活，也可以把时间留给真正感兴趣的地方。"}</p><div className={styles.classicAdjust}>{(isEn ? ["Dates", "Trip length", "Stay standard", "Vehicle", "Daily pace", "Destinations", "Local experiences"] : ["出发日期", "旅行天数", "住宿标准", "车辆", "每天节奏", "目的地", "当地体验"]).map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className={styles.classicSplit}><div className="shell"><div><p className={styles.classicEyebrow}>STAY & TRANSPORT</p><h2>{copy.stay}</h2><h3>{isEn ? "Stays" : props.locale === "zh-TW" ? "住宿" : "住宿"}</h3><p>{props.hotels}</p></div><div><h3>{isEn ? "Private car" : props.locale === "zh-TW" ? "私人用車" : "私人用车"}</h3><p>{isEn ? "Vehicles are arranged around group size and route: airport or rail transfers, daily private driving, and intercity travel." : "根据人数和路线安排车辆，可覆盖机场 / 高铁接送、每日包车及厦门、土楼、泉州之间的交通。"}</p></div></div></section>
    <section className={styles.classicSection}><div className="shell"><p className={styles.classicEyebrow}>WHAT’S INCLUDED</p><h2>{copy.included}</h2><div className={styles.classicColumns}><div><h3>{isEn ? "Can be arranged together" : "可以一起安排"}</h3><ul>{(isEn ? ["Private car", "Airport / rail transfers", "Stays", "Local experiences", "Route planning", "Trip support"] : ["私人用车", "机场 / 高铁接送", "住宿", "当地体验", "路线规划", "旅行中的行程协助"]).map((x) => <li key={x}>{x}</li>)}</ul></div><div><h3>{isEn ? "Confirmed to your needs" : "根据需求确认"}</h3><ul>{(isEn ? ["Attraction tickets", "Meals", "Guide / local companion", "Special experiences", "Children’s arrangements", "Other personal needs"] : ["景点门票", "餐食", "导游 / 当地陪同", "特殊体验", "儿童相关安排", "其他个人需求"]).map((x) => <li key={x}>{x}</li>)}</ul></div></div><p className={styles.classicNote}>{isEn ? "Final inclusions and exclusions follow the confirmed itinerary and quotation." : "最终包含与不包含项目，以确认后的行程方案和报价为准。"}</p></div></section>
    <section className={styles.classicSection}><div className="shell"><p className={styles.classicEyebrow}>IS THIS FOR YOU?</p><h2>{copy.forYou}</h2><ul className={styles.classicFit}>{(isEn ? ["First time in Fujian", "Around five days", "Couples / friends", "Family travel", "Travelling with parents", "No large group", "Help with transport and route"] : ["第一次来福建", "只有 5 天左右", "情侣 / 朋友", "家庭旅行", "带父母旅行", "不喜欢跟大团", "希望有人解决交通和路线"]).map((x) => <li key={x}>{x}</li>)}</ul><p>{isEn ? "Already seen Xiamen or have more than seven days? We can design a deeper Fujian route." : "如果你已经来过厦门，或者有 7 天以上时间，我们也可以重新设计一条更深入的福建路线。"}</p></div></section>
    <section className={styles.classicFaq}><div className="shell"><p className={styles.classicEyebrow}>FAQ</p><h2>{isEn ? "Questions before you go" : "出发前，先看看这些问题。"}</h2>{(isEn ? ["Will five days feel rushed?", "Can we add or remove destinations?", "Is it suitable for older travellers and children?", "Can we book hotels ourselves?", "How much does it cost?"] : ["五天会不会太赶？", "可以减少或增加目的地吗？", "带老人和孩子适合吗？", "酒店可以自己订吗？", "这条路线大概多少钱？"]).map((q, i) => <details key={q}><summary><span>0{i + 1}</span>{q}</summary><p>{i === 4 ? (isEn ? "It depends on group size, stay standard, vehicle, guiding, and experiences. Tell us your dates and needs first." : "价格会根据人数、住宿标准、车辆、是否需要导游以及具体体验而变化。告诉我们人数、日期和住宿需求后，再根据实际行程提供报价。") : (isEn ? ["The framework is calm and can be adjusted around your pace.", "Yes. We can change the days, route, and experiences.", "Yes. Walking, hotel changes, and daily rhythm can be adjusted.", "Yes. We can work with a hotel you have already booked."][i] : ["这条路线保留了调整空间，可以按同行人的节奏安排。", "可以，天数、路线和体验都可以沟通调整。", "适合，可以根据老人和孩子减少步行、调整节奏。", "可以，已经自行预订的酒店也可以纳入路线安排。"][i])}</p></details>)}</div></section>
    <section className={styles.classicFinal}><div className="shell"><p className={styles.classicEyebrow}>MAKE IT YOUR JOURNEY</p><h2>{copy.final}</h2><p>{isEn ? "Tell us when you are coming, who is travelling, and what you most want to see. We will reshape this five-day route around your trip." : "告诉我们什么时候来、几个人，以及哪些地方最想去。我们会在这条 5 日路线的基础上，根据你的时间和旅行方式重新调整。"}</p><a className={styles.classicPrimary} href={copy.plan}>{copy.contact}</a><a href="/trips">{isEn ? "See other Fujian routes →" : "查看其他福建路线 →"}</a><small>{isEn ? "An inquiry is not a booking." : "咨询不代表下单，确认路线和安排后再决定。"}</small></div></section>
    <aside className={styles.classicSticky}><span>{props.title}</span><small>{isEn ? "Xiamen → Tulou → Quanzhou · 5 days · Flexible" : "厦门 → 土楼 → 泉州 · 5天4晚 · 行程可调整"}</small><a className={styles.classicPrimary} href={copy.plan}>{isEn ? "Customize →" : "免费定制 →"}</a></aside>
    <a className={styles.classicMobileCta} href={copy.plan}>{isEn ? "Customize this journey →" : "定制这条路线 →"}</a>
  </main>;
}
