"use client";

import { useEffect } from "react";
import type { PublicLocale } from "./localized-home";

const localized = {
  "zh-CN": {
    brand: "中国定制旅行", label: "从兴趣出发", title: "不只到过中国，\n也真正走近中国。", intro: "文化体验不是行程里的装饰。我们从你的兴趣出发，把人物、地方与故事放回真实语境，再与路线、住宿和交通自然衔接。", compassLabel: "我们如何选择体验", compassTitle: "有内容，也有合适的节奏。", compassText: "先确认你为什么感兴趣，再判断地点、时间与同行成员是否合适。体验项目以最终确认和当地实际可安排资源为准。", principles: [["01", "从兴趣出发", "寻根、建筑、饮食或地方生活，都应回应旅行者真正想了解的内容。"], ["02", "让文化有上下文", "不只拍照打卡，也尽量说明一座建筑、一种习俗或一道菜为何在这里出现。"], ["03", "为同行者留余地", "根据长辈、孩子与行走能力调整节奏，不把一天塞满才算丰富。"]], action: "加入我的定制行程", ctaTitle: "从一个真正感兴趣的主题开始。", ctaText: "告诉我们同行成员、旅行时间和想深入了解的内容，再一起把体验放到合适的路线里。", cta: "填写定制需求",
    items: [
      ["/tulou.webp", "故乡重访与家族记忆", "对于已经知道祖籍村镇、祖居地址或拥有当地亲友联系方式的旅客，我们可以把故乡重访自然放进行程。沿着客户提供的记忆与地点，安排祖居周边、宗祠、老街、旧村或家族纪念地点，并衔接附近值得了解的村落与城市。让一次旅行成为重看故乡风景、陪伴长辈回忆往事，也让下一代认识家族来处的机会。具体访问内容会根据现有信息、交通和当地接待条件共同确认。", ["根据已有祖籍地点、旧址或当地联系人规划路线", "可安排祖居周边、宗祠、故乡街区与附近文化景点", "为亲友见面、家庭纪念与长辈休息保留充足时间", "可与福建其他城市和文化体验组合成完整行程"]],
      ["/hanfu.webp", "传统衣冠与东方美学", "福建的衣冠体验不只限于汉服。不同朝代的服饰形制、闽地传统妆饰，以及宁德、霞浦等闽东地区的畲族服饰，都承载着不同的历史、族群记忆与审美语言。我们会根据兴趣选择与文化背景相符的古城、传统村落、海岸、茶园或历史建筑；在霞浦等地，也可按当地实际资源讨论畲族服饰换装、妆造、非遗工艺了解或摄影体验。重点不是套用同一种造型，而是先理解服饰从哪里来，再让人物、环境与故事彼此呼应。", ["可选择汉服、地方传统装束或闽东畲族服饰等主题", "根据城市、村落、山海环境、季节与光线匹配场景", "服装租赁、妆造、摄影及文化讲解均需分别确认", "尊重民族服饰的文化含义，避免把不同传统混为一种风格"]],
      ["/kaiyuan-temple.webp", "信俗、寺院与传统建筑", "福建的精神文化版图远不止一座寺院。佛教寺院、妈祖信俗、陈靖姑信俗、保生大帝信俗、地方宫庙、道观、宗祠，以及海上丝绸之路留下的多元宗教遗存，共同连接着沿海航行、社区生活、家族组织与地方历史。可以从厦门、泉州、漳州延伸到莆田湄洲、福州、宁德、龙岩和闽北，围绕建筑、海洋信仰、民间传说或宗族礼俗形成不同路线。我们重视每处场所的时代背景与地方关系，而不是把寺庙简单列成打卡清单。", ["可围绕佛教建筑、妈祖文化、地方信俗、宗祠或海丝遗产选题", "把寺院、宫庙、街区和聚落放回当地历史脉络理解", "尊重宗教与民间信俗场所的着装、拍摄和参访礼仪", "开放范围、节庆活动与当地讲解以实际确认方案为准"]],
      ["/hero.webp", "福建聚落与侨乡故事", "从闽南红砖古厝、闽西客家聚落，到福州、莆仙、闽东和沿海侨乡，福建不同地区都留下了迁徙、经商、出海与返乡建设的痕迹。宗祠、祖厝、骑楼、番仔楼、侨批和旧街区，记录的不只是建筑风格，也包括家庭如何跨越海洋维系联系、汇款养家、兴办学校与建设故乡。走进村落、市场和社区，是为了看见福建内部的差异，也理解这些地方如何共同形成开放而重乡情的文化性格。", ["可按祖籍、建筑、华侨史或地方生活选择福建不同区域", "从祖厝、宗祠、侨宅与侨批延伸到具体家庭和迁徙故事", "结合老街、市场、港口或村落观察今天仍在延续的生活", "访问内容依兴趣、交通、开放条件与当地联系情况组合"]],
      ["/fujian-food.webp", "山海风味与地方餐桌", "福建的味道随着山海与城市变化。闽南可以从沙茶面、面线糊、海蛎煎、姜母鸭、五香卷和土笋冻认识港口往来、街巷小吃与日常饮食；福州的汤菜与鱼丸、莆仙风味、闽西客家菜、闽北山珍和武夷茶席，又呈现出完全不同的地方性格。我们会把餐食放进当天的路线与生活场景，而不是只列一张网红美食清单。", ["可按闽南小吃、海鲜、客家菜、茶文化或地方家常菜选题", "结合老街、市场、渔港、茶山或村落安排饮食体验", "提前确认过敏、忌口、宗教饮食与儿童需求", "具体餐厅、菜品和体验形式以季节及实际营业情况为准"]],
    ],
  },
  "zh-TW": {
    brand: "中國訂製旅行", label: "從興趣出發", title: "不只到過中國，\n也真正走近中國。", intro: "文化體驗不是行程裡的裝飾。我們從你的興趣出發，把人物、地方與故事放回真實語境，再與路線、住宿和交通自然銜接。", compassLabel: "我們如何選擇體驗", compassTitle: "有內容，也有合適的節奏。", compassText: "先確認你為什麼感興趣，再判斷地點、時間與同行成員是否合適。體驗項目以最終確認與當地實際可安排資源為準。", principles: [["01", "從興趣出發", "尋根、建築、飲食或地方生活，都應回應旅客真正想了解的內容。"], ["02", "讓文化有脈絡", "不只拍照打卡，也盡量說明一座建築、一種習俗或一道菜為何在這裡出現。"], ["03", "為同行者留餘地", "依照長輩、孩子與步行能力調整節奏，不把一天塞滿才算豐富。"]], action: "加入我的訂製行程", ctaTitle: "從一個真正感興趣的主題開始。", ctaText: "告訴我們同行成員、旅行時間與想深入了解的內容，再一起把體驗放進合適的路線。", cta: "填寫訂製需求",
    items: [
      ["/tulou.webp", "故鄉重訪與家族記憶", "對於已經知道祖籍村鎮、祖居地址或持有當地親友聯絡方式的旅客，我們可以把故鄉重訪自然放進行程。沿著旅客提供的記憶與地點，安排祖居周邊、宗祠、老街、舊村或家族紀念地點，並銜接附近值得了解的村落與城市。讓一次旅行成為重看故鄉風景、陪伴長輩回憶往事，也讓下一代認識家族來處的機會。具體訪問內容會依現有資訊、交通與當地接待條件共同確認。", ["依已有祖籍地點、舊址或當地聯絡人規劃路線", "可安排祖居周邊、宗祠、故鄉街區與附近文化景點", "為親友見面、家庭紀念與長輩休息保留充足時間", "可與福建其他城市和文化體驗組合成完整行程"]],
      ["/hanfu.webp", "傳統衣冠與東方美學", "福建的衣冠體驗不只限於漢服。不同朝代的服飾形制、閩地傳統妝飾，以及寧德、霞浦等閩東地區的畲族服飾，都承載著不同的歷史、族群記憶與審美語言。我們會依興趣選擇與文化背景相符的古城、傳統村落、海岸、茶園或歷史建築；在霞浦等地，也可依當地實際資源討論畲族服飾換裝、妝造、非遺工藝了解或攝影體驗。重點不是套用同一種造型，而是先理解服飾從何而來，再讓人物、環境與故事彼此呼應。", ["可選擇漢服、地方傳統裝束或閩東畲族服飾等主題", "依城市、村落、山海環境、季節與光線搭配場景", "服裝租借、妝造、攝影及文化解說均須分別確認", "尊重民族服飾的文化意義，避免把不同傳統混為一種風格"]],
      ["/kaiyuan-temple.webp", "信俗、寺院與傳統建築", "福建的精神文化版圖遠不只一座寺院。佛教寺院、媽祖信俗、陳靖姑信俗、保生大帝信俗、地方宮廟、道觀、宗祠，以及海上絲綢之路留下的多元宗教遺存，共同連結著沿海航行、社區生活、家族組織與地方歷史。可以從廈門、泉州、漳州延伸至莆田湄洲、福州、寧德、龍巖和閩北，圍繞建築、海洋信仰、民間傳說或宗族禮俗形成不同路線。我們重視每處場所的時代背景與地方關係，而不是把寺廟簡單列成打卡清單。", ["可圍繞佛教建築、媽祖文化、地方信俗、宗祠或海絲遺產選題", "把寺院、宮廟、街區和聚落放回當地歷史脈絡理解", "尊重宗教與民間信俗場所的服裝、拍攝和參訪禮儀", "開放範圍、節慶活動與當地解說以實際確認方案為準"]],
      ["/hero.webp", "福建聚落與僑鄉故事", "從閩南紅磚古厝、閩西客家聚落，到福州、莆仙、閩東和沿海僑鄉，福建不同地區都留下了遷徙、經商、出海與返鄉建設的痕跡。宗祠、祖厝、騎樓、番仔樓、僑批和舊街區，記錄的不只是建築風格，也包括家庭如何跨越海洋維繫聯繫、匯款養家、興辦學校與建設故鄉。走進村落、市場和社區，是為了看見福建內部的差異，也理解這些地方如何共同形成開放而重鄉情的文化性格。", ["可依祖籍、建築、華僑史或地方生活選擇福建不同區域", "從祖厝、宗祠、僑宅與僑批延伸至具體家庭和遷徙故事", "結合老街、市場、港口或村落觀察今天仍在延續的生活", "訪問內容依興趣、交通、開放條件與當地聯繫情況組合"]],
      ["/fujian-food.webp", "山海風味與地方餐桌", "福建的味道隨著山海與城市變化。閩南可以從沙茶麵、麵線糊、海蠣煎、薑母鴨、五香卷和土筍凍認識港口往來、街巷小吃與日常飲食；福州的湯菜與魚丸、莆仙風味、閩西客家菜、閩北山珍和武夷茶席，又呈現出完全不同的地方性格。我們會把餐食放進當天的路線與生活場景，而不是只列一張熱門美食清單。", ["可依閩南小吃、海鮮、客家菜、茶文化或地方家常菜選題", "結合老街、市場、漁港、茶山或村落安排飲食體驗", "提前確認過敏、忌口、宗教飲食與兒童需求", "具體餐廳、菜色和體驗形式以季節及實際營業情況為準"]],
    ],
  },
  en: {
    brand: "Custom China Travel", label: "START WITH YOUR INTERESTS", title: "Go beyond seeing China.\nGet closer to it.", intro: "Culture should not feel like an add-on. We connect the people, places, and stories behind each experience, then fit it naturally into your route.", compassLabel: "HOW WE CHOOSE EXPERIENCES", compassTitle: "Meaningful, practical, and well paced.", compassText: "We begin with what interests you, then consider the place, timing, and travel party. Every experience remains subject to confirmation and local availability.", principles: [["01", "Start with curiosity", "Ancestry, architecture, food, and local life should answer something you genuinely want to understand."], ["02", "Give culture context", "Go beyond photos to understand why a building, custom, or dish belongs to its place."], ["03", "Leave room to enjoy it", "Adjust the pace for children, older travellers, and walking needs instead of filling every hour."]], action: "Add to my custom trip", ctaTitle: "Start with one subject you care about.", ctaText: "Share your group, dates, and interests. We will place the experience where it fits naturally.", cta: "Plan a custom trip",
    items: [
      ["/tulou.webp", "Returning to family roots", "If you already know your ancestral town, former home address, or local family contacts, we can build a hometown visit naturally into the trip. Using the places and memories you share, the route may include the area around an ancestral home, a clan hall, an old street, a former village, or a family memorial site, together with nearby cultural stops. It can be a chance for older relatives to revisit familiar landscapes and for younger family members to understand where their story began. Visits are planned around the information available, transport, and local access.", ["Plan around a known hometown, former address, or local contact", "Include ancestral neighborhoods, clan halls, old streets, and nearby heritage", "Leave enough time for family meetings, shared memories, and older travellers", "Combine the visit with other Fujian cities and cultural experiences"]],
      ["/hanfu.webp", "Traditional dress and regional aesthetics", "Dress experiences in Fujian extend beyond hanfu. Historical Chinese clothing, regional styling, and the She ethnic dress traditions of eastern Fujian each carry distinct histories and cultural meanings. We can match the subject with an old town, traditional village, coast, tea garden, or historic building. In Xiapu and nearby areas, She clothing, styling, craft interpretation, or photography may also be considered when suitable local resources are available. The aim is not to apply one costume everywhere, but to understand where a tradition comes from and let the person, setting, and story belong together.", ["Choose from hanfu, regional dress, or She clothing themes where appropriate", "Match the setting to the city, village, coast, season, and natural light", "Confirm clothing, styling, photography, and interpretation separately", "Respect the meaning of ethnic dress instead of blending distinct traditions together"]],
      ["/kaiyuan-temple.webp", "Belief, temples, and traditional architecture", "Fujian's spiritual landscape reaches far beyond a single temple. Buddhist monasteries, Mazu traditions, local deities, community shrines, Daoist sites, clan halls, and the diverse religious heritage of the Maritime Silk Road connect seafaring, neighborhood life, kinship, and regional history. Routes can extend from Xiamen, Quanzhou, and Zhangzhou to Meizhou in Putian, Fuzhou, Ningde, Longyan, and northern Fujian, with a focus on architecture, maritime belief, local stories, or ancestral customs. Each site is placed in its own time and community rather than treated as another stop on a checklist.", ["Choose a theme such as Buddhism, Mazu culture, local belief, clan halls, or maritime heritage", "Read temples, streets, and settlements within their local historical context", "Respect dress, photography, worship, and visitor etiquette", "Confirm opening hours, festivals, and local interpretation in the final plan"]],
      ["/hero.webp", "Fujian communities and migration stories", "From red-brick homes in southern Fujian and Hakka settlements in the west to Fuzhou, Putian, eastern Fujian, and coastal hometowns of overseas Chinese, the province records many histories of migration, trade, departure, and return. Ancestral homes, clan halls, arcades, hybrid mansions, remittance letters, and old neighborhoods reveal how families stayed connected across the sea, supported relatives, founded schools, and rebuilt their hometowns. Visiting villages, markets, and communities shows both Fujian's regional differences and the shared importance of family and outward exchange.", ["Choose regions around ancestry, architecture, overseas-Chinese history, or local life", "Connect homes, halls, migration-era buildings, and letters with personal stories", "Observe living culture in streets, markets, ports, and villages", "Shape visits around interests, transport, access, and local contacts"]],
      ["/fujian-food.webp", "Fujian flavors and local tables", "Fujian's food changes with its mountains, coast, and cities. Southern Fujian offers street and port-city favorites such as satay noodles, mianxianhu noodle soup, oyster omelet, ginger duck, five-spice rolls, and tusundong sea-worm aspic. Fuzhou soups and fish balls, Putian cooking, western Fujian Hakka dishes, northern mountain produce, and Wuyi tea reveal very different regional traditions. Meals are fitted into the day's route and local setting rather than treated as a viral-food checklist.", ["Choose a focus such as Minnan snacks, seafood, Hakka food, tea, or home cooking", "Connect food with old streets, markets, fishing ports, tea hills, or villages", "Confirm allergies, dietary restrictions, religious needs, and children's meals", "Restaurants, dishes, and activities depend on season and actual opening conditions"]],
    ],
  },
} as const;

export default function LocalizedExperiences({ locale }: { locale: PublicLocale }) {
  const t = localized[locale];
  const root = locale === "zh-CN" ? "" : locale === "en" ? "/en" : "/zh-tw";
  useEffect(() => { document.documentElement.lang = locale === "en" ? "en" : locale === "zh-TW" ? "zh-Hant" : "zh-Hans"; }, [locale]);
  return <main className="experience-page" lang={locale === "en" ? "en" : locale === "zh-TW" ? "zh-Hant" : "zh-Hans"}>
    <section className="experience-hero shell"><p className="overline dark">{t.label}</p><h1>{t.title.split("\n").map((line,index)=><span key={line}>{line}{index===0&&<><br/>{" "}</>}</span>)}</h1><p>{t.intro}</p></section>
    <section className="experience-compass shell"><div className="experience-compass-head"><div><p className="overline dark">{t.compassLabel}</p><h2>{t.compassTitle}</h2></div><p>{t.compassText}</p></div><div className="experience-compass-grid">{t.principles.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="experience-list shell">{t.items.map((item,index)=><article key={item[1]}><div className="experience-photo"><img src={item[0]} alt={item[1]}/></div><div><span>0{index+1}</span><h2>{item[1]}</h2><p>{item[2]}</p><ul>{item[3].map(point=><li key={point}>{point}</li>)}</ul><a href={`${root}/plan`}>{t.action} →</a></div></article>)}</section>
    <section className="experience-cta"><div className="shell"><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><a href={`${root}/plan`}>{t.cta}</a></div></section>
  </main>;
}
