import type { PublicLocale } from "./localized-home";
import styles from "./vehicles/page.module.css";

const localized={
  "zh-CN":{eyebrow:"包车与接送",title:"合适的车，\n让路上也舒服。",intro:"从机场接送、城市包车到跨城行程，我们会结合人数、行李、路线和乘坐偏好协调车辆。国产新能源商务车与SUV、传统商务MPV及中大型车辆都可选择，具体车型会在方案中确认。",action:"咨询包车安排",
    heroFacts:[["按需选择","新能源、油车及不同级别均可协调"],["车型透明","确认品牌、型号或约定的同级车型"],["全程衔接","接送节点、用车时长与费用写清楚"]],
    fleetLabel:"车型选择",fleetTitle:"不是把车堆在页面上，而是讲清楚每类车适合谁。",fleetIntro:"以下为常见车型级别和代表车型。客户可按熟悉度、乘坐体验、人数和路线自由选择，不设单一默认答案。",
    vehicles:[
      ["01","国产新能源商务MPV","建议1–5位旅客","腾势D9・岚图梦想家・小鹏X9・极氪009","适合想体验中国智能电车的家庭或商务小团。安静座舱、舒适座椅、车载冰箱和娱乐屏等配置，以具体车型为准。"],
      ["02","国产新能源SUV","建议1–4位旅客","问界M9/M7・理想L9/L8・蔚来ES8・比亚迪唐","适合人数较少、希望兼顾空间与智能座舱的行程；携带较多大件行李时需另行核对后备厢。"],
      ["03","传统商务MPV","建议1–5位旅客","别克GL8・丰田埃尔法・奔驰V级或同级","适合偏好熟悉车型、商务接待或多日城市行程的客户，油车及其他指定偏好也可沟通。"],
      ["04","中型团队用车","建议8–20位旅客","宇通T7・丰田柯斯达或同级","适合亲友团、小型团队、会议接送和区域环线，并按人数预留行李空间。"],
      ["05","大型旅游巴士","建议20人以上","新能源或燃油旅游巴士","适合大型团队和多日环线，按路线距离、道路条件、补能条件和行李量确定车辆。"]
    ],
    featureLabel:"中国新能源体验",featureTitle:"让海外旅客在旅途中，体验中国智能座舱。",featureText:"对感兴趣的客户，可在条件允许时选择国产新能源MPV或SUV。页面只介绍这种可选体验，不替客户预设车型。",features:[["更安静","电驱车型在城市行驶和启停时通常更安静。"],["更舒适","部分车型提供二排舒适座椅、通风、加热或按摩。"],["更智能","部分车型配有车载冰箱、娱乐屏和智能语音等配置。"]],
    serviceLabel:"不只是一辆车",serviceTitle:"把每个接送节点写进行程。",services:[["01","到达接应","提前核对航班或车次、到达时间、接应点和酒店地址。"],["02","每日用车","结合游览顺序、停留时间、步行距离与同行者需求。"],["03","跨城衔接","协调福建及全国多城之间的车辆与司机服务。"]],
    standardsLabel:"出发前确认",standardsTitle:"车型、时间和费用，都要有明确答案。",standards:[["车辆信息","确认品牌或同级车型、能源类型、座位数、行李空间及车况要求。"],["司机与时间","确认接应人、电话、服务时长、等候规则和集合点。"],["费用范围","明确能源费或油费、路桥费、停车费、司机餐宿和超时费用。"]],note:"页面车型仅用于说明常见车辆级别和乘坐体验，不代表出行时一定能提供该品牌或型号。实际车辆以出行城市、日期、人数、当地车辆资源及最终行程确认单为准；如需指定车型，请在确认方案前单独提出并以最终回复为准。",ctaTitle:"告诉我们人数、行李和偏好的乘坐体验。",ctaText:"想体验国产新能源车，或偏好熟悉的传统车型，都可以在方案中说明。",cta:"填写定制需求"},
  "zh-TW":{eyebrow:"包車與接送",title:"合適的車，\n讓路上也舒適。",intro:"從機場接送、市區包車到跨城行程，我們會結合人數、行李、路線與乘坐偏好協調車輛。國產新能源商務車與SUV、傳統商務MPV及中大型車輛皆可選擇，具體車型會在方案中確認。",action:"諮詢包車安排",
    heroFacts:[["按需選擇","新能源、燃油車與不同級別皆可協調"],["車型透明","確認品牌、型號或約定的同級車型"],["全程銜接","接送節點、用車時長與費用寫清楚"]],
    fleetLabel:"車型選擇",fleetTitle:"不把車堆在頁面上，而是說清楚每類車適合誰。",fleetIntro:"以下為常見車型級別與代表車型。旅客可依熟悉度、乘坐體驗、人數與路線自由選擇，不設單一預設答案。",
    vehicles:[["01","國產新能源商務MPV","建議1–5位旅客","騰勢D9・嵐圖夢想家・小鵬X9・極氪009","適合想體驗中國智能電動車的家庭或商務小團。安靜座艙、舒適座椅、車載冰箱與娛樂螢幕等配置，以具體車型為準。"],["02","國產新能源SUV","建議1–4位旅客","問界M9/M7・理想L9/L8・蔚來ES8・比亞迪唐","適合人數較少、希望兼顧空間與智能座艙的行程；攜帶較多大型行李時需另行核對行李廂。"],["03","傳統商務MPV","建議1–5位旅客","別克GL8・豐田埃爾法・賓士V級或同級","適合偏好熟悉車型、商務接待或多日市區行程的旅客，燃油車與其他指定偏好亦可溝通。"],["04","中型團隊用車","建議8–20位旅客","宇通T7・豐田柯斯達或同級","適合親友團、小型團隊、會議接送與區域環線，並依人數預留行李空間。"],["05","大型旅遊巴士","建議20人以上","新能源或燃油旅遊巴士","適合大型團隊與多日環線，依路線距離、道路條件、補能條件與行李量確定車輛。"]],
    featureLabel:"中國新能源體驗",featureTitle:"讓海外旅客在旅途中，體驗中國智能座艙。",featureText:"對有興趣的旅客，可在條件允許時選擇國產新能源MPV或SUV。頁面只介紹這項可選體驗，不替旅客預設車型。",features:[["更安靜","電驅車型在市區行駛與啟停時通常更安靜。"],["更舒適","部分車型提供二排舒適座椅、通風、加熱或按摩。"],["更智能","部分車型配有車載冰箱、娛樂螢幕與智能語音等配置。"]],
    serviceLabel:"不只是一輛車",serviceTitle:"把每個接送節點寫進行程。",services:[["01","抵達接應","提前核對航班或車次、抵達時間、接應點與飯店地址。"],["02","每日用車","結合遊覽順序、停留時間、步行距離與同行者需求。"],["03","跨城銜接","協調福建及全國多城之間的車輛與司機服務。"]],
    standardsLabel:"出發前確認",standardsTitle:"車型、時間與費用，都要有明確答案。",standards:[["車輛資訊","確認品牌或同級車型、能源類型、座位數、行李空間與車況要求。"],["司機與時間","確認接應人、電話、服務時長、等候規則與集合點。"],["費用範圍","明確能源費或油費、路橋費、停車費、司機餐宿與超時費用。"]],note:"頁面車型僅用於說明常見車輛級別與乘坐體驗，不代表旅行時一定能提供該品牌或型號。實際車輛以旅行城市、日期、人數、當地車輛資源及最終行程確認單為準；如需指定車型，請在確認方案前另行提出並以最終回覆為準。",ctaTitle:"告訴我們人數、行李與偏好的乘坐體驗。",ctaText:"想體驗國產新能源車，或偏好熟悉的傳統車型，都可在方案中說明。",cta:"填寫訂製需求"},
  en:{eyebrow:"Private vehicles",title:"The right vehicle\nmakes the road comfortable.",intro:"From airport transfers and vehicles by day to intercity travel, we coordinate around the group, luggage, route and personal preference. Chinese new-energy MPVs and SUVs, familiar executive MPVs and group vehicles are all available options, with the model confirmed in the plan.",action:"Ask about vehicles",
    heroFacts:[["Chosen for you","New-energy, fuel and different vehicle classes"],["Model clarity","A named model or an agreed equivalent"],["Planned throughout","Transfers, service hours and costs stated clearly"]],
    fleetLabel:"Vehicle choices",fleetTitle:"Clear categories, not a wall of car photos.",fleetIntro:"These are common vehicle classes and representative models. Travellers can choose around familiarity, comfort, group size and route; there is no single default answer.",
    vehicles:[["01","Chinese new-energy MPVs","Best for 1–5 travellers","Denza D9 · VOYAH Dream · XPENG X9 · ZEEKR 009","For families or business groups curious about China's intelligent EV experience. Quiet cabins, comfort seats, refrigerators and entertainment screens depend on the exact model."],["02","Chinese new-energy SUVs","Best for 1–4 travellers","AITO M9/M7 · Li L9/L8 · NIO ES8 · BYD Tang","For smaller groups wanting space and an intelligent cabin. Larger luggage loads require a separate boot-space check."],["03","Familiar executive MPVs","Best for 1–5 travellers","Buick GL8 · Toyota Alphard · Mercedes-Benz V-Class or equivalent","For travellers who prefer familiar models, business hosting or multiday city travel. Fuel vehicles and other preferences can be requested."],["04","Mid-sized group vehicles","Best for 8–20 travellers","Yutong T7 · Toyota Coaster or equivalent","For extended families, small groups, events and regional circuits, with luggage capacity reserved."],["05","Touring coaches","Best for groups over 20","New-energy or fuel touring coaches","For larger groups and multiday circuits, selected around distance, roads, charging access and luggage."]],
    featureLabel:"A Chinese EV experience",featureTitle:"Experience China's intelligent cabins while travelling.",featureText:"Travellers who are interested may choose a Chinese new-energy MPV or SUV where available. This is an option, never a preference assumed on their behalf.",features:[["Quieter","Electric drive is generally quieter in city traffic and stop-start travel."],["More comfortable","Some models offer second-row comfort seats, ventilation, heating or massage."],["More connected","Some models include a refrigerator, entertainment screens and intelligent voice controls."]],
    serviceLabel:"More than a vehicle",serviceTitle:"Place every transfer in the itinerary.",services:[["01","Arrival meeting","Confirm the flight or train, arrival time, meeting point and hotel address."],["02","Vehicle by day","Plan around visit order, stop times, walking distance and travellers."],["03","Intercity connections","Coordinate vehicles and drivers across Fujian and wider China."]],
    standardsLabel:"Before departure",standardsTitle:"Clear answers on the model, timing and price.",standards:[["Vehicle details","Confirm the brand or equivalent, energy type, seats, luggage space and condition requirements."],["Driver and timing","Confirm the meeting contact, phone, service hours, waiting rules and meeting point."],["What the price includes","State energy or fuel, tolls, parking, driver meals or lodging and overtime clearly."]],note:"Models on this page illustrate common vehicle classes and ride experiences only; a specific brand or model is not guaranteed. The actual vehicle is subject to the city, date, group size, local fleet and final confirmed itinerary. Any model request must be raised before confirmation and remains subject to our final reply.",ctaTitle:"Share the group, luggage and preferred ride experience.",ctaText:"Choose a Chinese new-energy experience or a familiar conventional model in the plan.",cta:"Start planning"}
} as const;

export default function LocalizedVehiclesPage({locale}:{locale:PublicLocale}){
  const t=localized[locale];const root=locale==="zh-TW"?"/zh-tw":locale==="en"?"/en":"";const lang=locale==="zh-TW"?"zh-Hant":locale==="en"?"en":"zh-Hans";
  return <main lang={lang} className={`standalone-info-page ${styles.page}`}>
    <section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div className={styles.heroCopy}><p className="overline">{t.eyebrow}</p><h1>{t.title.split("\n").map(line=><span key={line}>{line}</span>)}</h1><p>{t.intro}</p><a href={`${root}/plan`}>{t.action} →</a></div><div className={styles.heroBoard}>{t.heroFacts.map(([title,text],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div></div></section>
    <section className={`shell ${styles.fleet}`}><header className={styles.sectionHead}><div><p className="overline">{t.fleetLabel}</p><h2>{t.fleetTitle}</h2></div><p>{t.fleetIntro}</p></header><div className={styles.vehicleGrid}>{t.vehicles.map(([n,title,recommend,models,text])=><article key={n}><span>{n}</span><div className={styles.vehicleHeading}><h3>{title}</h3><strong>{recommend}</strong></div><div className={styles.vehicleDetail}><b>{models}</b><p>{text}</p></div></article>)}</div><p className={styles.note}>{t.note}</p></section>
    <section className={styles.feature}><div className="shell"><header><p className="overline">{t.featureLabel}</p><h2>{t.featureTitle}</h2><p>{t.featureText}</p></header><div>{t.features.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className={styles.service}><div className="shell"><header><p className="overline">{t.serviceLabel}</p><h2>{t.serviceTitle}</h2></header><div>{t.services.map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className={`shell ${styles.standards}`}><header><p className="overline">{t.standardsLabel}</p><h2>{t.standardsTitle}</h2></header><div>{t.standards.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.cta}><div className="shell"><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><a href={`${root}/plan`}>{t.cta} →</a></div></section>
  </main>;
}
