"use client";

import Image from "next/image";
import { FormEvent, useEffect, useRef, useState } from "react";

export type PublicLocale = "zh-CN" | "zh-TW" | "en";

const images = {
  routes: ["/trip-xiamen-gulangyu.webp", "/route-pingtan-enhanced-v1.webp", "/route-quanzhou-natural-v3.webp"],
  destinations: ["/trip-xiamen-huandao.webp", "/trip-quanzhou-hero.webp", "/about-fujian-tulou.jpg", "/route-pingtan-enhanced-v1.webp", ""],
  experiences: ["/about-fujian-tulou.jpg", "/fujian-food.webp", "/trip-quanzhou-hero.webp", "/hanfu.webp", "/trip-quanzhou-xunpu.webp"],
} as const;

const V1 = {
  "zh-CN": {
    heroLabel: "福建 · FUJIAN",
    heroTitle: "第一次来福建，\n就让福建人带你玩。",
    heroText: "从厦门的海，到泉州的古城、土楼的村落和平潭的海岸。按照你和家人的时间与节奏，设计属于你们的福建旅程。",
    primary: "开始规划福建旅行",
    secondary: "和旅行顾问聊聊",
    heroNote: "私人定制 · 私人用车 · 行程灵活 · 不默认安排购物",
    journeyLabel: "CURATED JOURNEYS",
    journeyTitle: "第一次来福建，\n从这里开始。",
    journeyIntro: "不知道福建怎么玩没关系。我们先准备了几条适合第一次来福建的路线，你可以直接参考，也可以按照自己的时间和喜好调整。",
    journeys: [
      ["01", "福建经典 · 5日", "厦门 → 鼓浪屿 → 福建土楼 → 泉州", "FIRST TIME IN FUJIAN\n第一次来福建推荐", "第一次来福建，这样玩刚刚好。", "从厦门的海开始，走进鼓浪屿的老街，住进福建土楼的山谷，再到泉州感受闽南文化。五天时间，不赶路，也不会错过福建最值得认识的地方。", "鼓浪屿 / 福建土楼 / 泉州古城 / 闽南美食", "5天 · 私人用车 · 行程可调整", "查看5日行程"],
      ["02", "山海福建 · 7日", "厦门 → 泉州 → 平潭 → 福建土楼", "COAST & CULTURE\n山海与人文", "多两天，看看福建真正的山与海。", "从泉州古城一路走向平潭海岸，再进入福建土楼与山村。适合不想只打卡景点，而是希望慢一点认识福建的人。", "泉州古城 / 平潭海岸 / 福建土楼 / 当地生活", "7天 · 私人用车 · 节奏自由", "查看7日行程"],
      ["03", "福建家庭私人游 · 6日", "厦门 → 鼓浪屿 → 福建土楼 → 泉州", "FAMILY PRIVATE TOUR\n家庭旅行", "带父母和孩子，也可以轻松玩福建。", "减少赶路和频繁换酒店，根据老人和孩子的节奏安排每天的行程。私人用车、接送和住宿一起规划，让一家人把时间真正留给旅行。", "家庭友好 / 私人用车 / 减少赶路 / 行程灵活", "6天 · 适合家庭 · 可按年龄调整", "查看家庭路线"],
    ],
    journeyFooterTitle: "没有适合你的路线？",
    journeyFooterText: "告诉我们你有几天、和谁一起旅行，我们可以从零开始帮你设计。",
    journeyFooterCta: "免费规划我的福建旅行",
    destinationLabel: "EXPLORE FUJIAN",
    destinationTitle: "福建不只有厦门。",
    destinationIntro: "海岛、古城、土楼、茶山和村落，不同的福建，适合不同的旅行方式。",
    destinations: [["XIAMEN", "厦门", "海岛、老街与轻松的滨海生活", "海滨城市 · 鼓浪屿 · 美食"], ["QUANZHOU", "泉州", "在古城里，看见真正的闽南", "世界遗产 · 闽南文化 · 古城"], ["FUJIAN TULOU", "福建土楼", "住进山谷，认识福建另一种生活", "世界遗产 · 村落 · 客家文化"], ["PINGTAN", "平潭", "沿着海岸公路，去看福建最蓝的海", "海岛 · 海岸 · 日落"], ["WUYI MOUNTAIN", "武夷山", "山水、茶园和慢下来的几天", "山水 · 武夷岩茶 · 徒步"]],
    explore: "探索",
    destinationCta: "探索福建目的地",
    experienceLabel: "BEYOND SIGHTSEEING",
    experienceTitle: "福建，不只是\n来看风景。",
    experienceIntro: "有些福建，藏在一顿饭、一座老房子、\n一句乡音和当地人的日常里。",
    rootsMeta: "01",
    rootsLabel: "ROOTS JOURNEY",
    rootsName: "福建寻根",
    rootsTitle: "回来看看，故事开始的地方。",
    rootsText: "如果你的家族来自福建，我们可以根据祖籍地、姓氏和已有线索，协助规划一次回乡与寻根旅程。",
    rootsKeywords: "祖籍村落 · 宗祠 · 家族线索 · 故乡探访",
    rootsCta: "了解福建寻根",
    experiences: [["FUJIAN FOOD", "福建味道", "不只是找一家网红餐厅，而是从小吃、茶和当地人的餐桌，慢慢认识福建的味道。"], ["MINNAN CULTURE", "闽南文化", "从泉州古城、寺庙、红砖古厝到地方信俗，看看闽南文化如何融入今天的生活。"], ["TRADITIONAL DRESS", "传统服饰", "了解福建不同地方的传统服饰与审美，也可以根据兴趣安排体验与拍摄。"], ["LOCAL LIFE", "当地生活", "市场、茶馆、老街、村落和社区，旅行不一定每天都要赶景点。"]],
    emotionalLabel: "TRAVEL DEEPER INTO FUJIAN",
    emotionalTitle: "真正记住的，\n往往不是景点。",
    emotionalText: "可能是一顿饭，\n一句熟悉的乡音，\n一座老房子，\n或是一段你原本不知道的家族故事。",
    serviceLabel: "TRAVEL MADE SIMPLE",
    serviceTitle: "你负责来福建，\n剩下的我们一起安排。",
    serviceIntro: "不用同时找司机、酒店、路线和当地体验。告诉我们你想怎么玩，我们把整段旅程串起来。",
    services: [["PRIVATE CAR", "私人用车", "机场接送、每日包车、城市之间的交通，按照人数和路线安排合适车辆。"], ["STAYS", "住宿安排", "根据预算、位置和旅行方式推荐住宿，不默认绑定固定酒店。"], ["PICKUP", "机场 / 高铁接送", "厦门机场、高铁站及主要交通节点，均可根据最终行程安排接送。"], ["LOCAL EXPERIENCES", "当地体验", "美食、文化、村落、茶、寻根等体验，都可以加入私人行程。"], ["TRIP SUPPORT", "行程协助", "从出发前规划到旅行中的调整，都有真人可以联系。"]],
    aboutLabel: "LOCAL TEAM · REAL FUJIAN",
    aboutTitle: "我们就在福建。",
    aboutText: "TripFujian 是一个来自福建的本地旅行团队。\n\n我们熟悉这里的路线、交通、住宿和旅行节奏，也希望让第一次来到福建的人，少一点陌生，多一点安心。\n\n我们不希望把每个人塞进同一条固定路线。告诉我们什么时候来、和谁一起、喜欢什么，再一起把旅程设计出来。",
    trustPoints: [["01 福建本地 / LOCAL IN FUJIAN", "熟悉福建主要目的地、交通方式和旅行节奏。"], ["02 真人沟通 / REAL PEOPLE", "从第一次咨询开始，由真人与你沟通旅行需求。"], ["03 行程透明 / CLEAR ITINERARY", "路线、住宿、车辆和相关费用，在确认方案时说明清楚。"], ["04 私人定制 / MADE FOR YOU", "根据人数、时间、预算和兴趣调整行程。"]],
    aboutCtaTitle: "第一次找我们旅行？",
    aboutCtaText: "第一次联系一家福建本地旅行团队，有疑问很正常。你可以先告诉我们大概什么时候来、几个人、想去哪些地方。我们先帮你看看路线是否合理，咨询不代表必须预订。",
    aboutCta: "先聊聊我的福建旅行",
    faqLabel: "出发前常见问题 ◆ FAQ",
    plannerLabel: "开始你的旅程 ◆ PLAN YOUR TRIP",
    plannerTitle: "告诉我们，\n你想怎么玩福建。",
    plannerText: "不需要马上决定路线，也不需要立即付款。告诉我们日期、人数和想去的地方，我们先帮你整理旅行方向。",
    plannerCta: "开始规划我的福建旅行",
  },
  "zh-TW": {
    heroLabel: "福建 · FUJIAN", heroTitle: "第一次來福建，\n就讓福建人帶你玩。", heroText: "從廈門的海，到泉州的古城、土樓的村落和平潭的海岸。按照你和家人的時間與節奏，設計屬於你們的福建旅程。", primary: "開始規劃福建旅行", secondary: "WhatsApp 聯絡顧問", heroNote: "私人訂製 · 私人用車 · 行程彈性 · 不預設安排購物",
    journeyLabel: "CURATED JOURNEYS", journeyTitle: "第一次來福建，\n從這裡開始。", journeyIntro: "不知道福建怎麼玩也沒關係。我們先準備了幾條適合第一次來福建的路線，你可以直接參考，也可以依自己的時間和喜好調整。", journeys: [["01", "福建經典 · 5日", "廈門 → 鼓浪嶼 → 福建土樓 → 泉州", "FIRST TIME IN FUJIAN\n第一次來福建推薦", "第一次來福建，這樣玩剛剛好。", "從廈門的海開始，走進鼓浪嶼的老街，住進福建土樓的山谷，再到泉州感受閩南文化。五天時間，不趕路，也不會錯過福建最值得認識的地方。", "鼓浪嶼 / 福建土樓 / 泉州古城 / 閩南美食", "5天 · 私人用車 · 行程可調整", "查看5日行程"], ["02", "山海福建 · 7日", "廈門 → 泉州 → 平潭 → 福建土樓", "COAST & CULTURE\n山海與人文", "多兩天，看看福建真正的山與海。", "從泉州古城一路走向平潭海岸，再進入福建土樓與山村。適合不想只打卡景點，而是希望慢一點認識福建的人。", "泉州古城 / 平潭海岸 / 福建土樓 / 在地生活", "7天 · 私人用車 · 節奏自由", "查看7日行程"], ["03", "福建家庭私人遊 · 6日", "廈門 → 鼓浪嶼 → 福建土樓 → 泉州", "FAMILY PRIVATE TOUR\n家庭旅行", "帶父母和孩子，也可以輕鬆玩福建。", "減少趕路和頻繁更換飯店，依長輩和孩子的節奏安排每天的行程。私人用車、接送和住宿一起規劃，讓一家人把時間真正留給旅行。", "家庭友善 / 私人用車 / 減少趕路 / 行程彈性", "6天 · 適合家庭 · 可依年齡調整", "查看家庭路線"]], journeyFooterTitle: "沒有適合你的路線？", journeyFooterText: "告訴我們你有幾天、和誰一起旅行，我們可以從零開始幫你設計。", journeyFooterCta: "免費規劃我的福建旅行",
    destinationLabel: "EXPLORE FUJIAN", destinationTitle: "福建不只有廈門。", destinationIntro: "海島、古城、土樓、茶山和村落，不同的福建，適合不同的旅行方式。", destinations: [["XIAMEN", "廈門", "海島、老街與輕鬆的濱海生活", "濱海城市 · 鼓浪嶼 · 美食"], ["QUANZHOU", "泉州", "在古城裡，看見真正的閩南", "世界遺產 · 閩南文化 · 古城"], ["FUJIAN TULOU", "福建土樓", "住進山谷，認識福建另一種生活", "世界遺產 · 村落 · 客家文化"], ["PINGTAN", "平潭", "沿著海岸公路，去看福建最藍的海", "海島 · 海岸 · 日落"], ["WUYI MOUNTAIN", "武夷山", "山水、茶園和慢下來的幾天", "山水 · 武夷岩茶 · 健行"]], explore: "探索", destinationCta: "探索福建目的地",
    experienceLabel: "BEYOND SIGHTSEEING", experienceTitle: "福建，不只是\n來看風景。", experienceIntro: "有些福建，藏在一頓飯、一座老房子、\n一句鄉音和在地人的日常裡。", rootsMeta: "01", rootsLabel: "ROOTS JOURNEY", rootsName: "福建尋根", rootsTitle: "回來看看，故事開始的地方。", rootsText: "如果你的家族來自福建，我們可以依祖籍地、姓氏和已有線索，協助規劃一次返鄉與尋根旅程。", rootsKeywords: "祖籍村落 · 宗祠 · 家族線索 · 故鄉探訪", rootsCta: "了解福建尋根", experiences: [["FUJIAN FOOD", "福建味道", "不只是找一家網紅餐廳，而是從小吃、茶和在地人的餐桌，慢慢認識福建的味道。"], ["MINNAN CULTURE", "閩南文化", "從泉州古城、寺廟、紅磚古厝到地方信俗，看看閩南文化如何融入今天的生活。"], ["TRADITIONAL DRESS", "傳統服飾", "了解福建不同地方的傳統服飾與審美，也可以依興趣安排體驗與拍攝。"], ["LOCAL LIFE", "在地生活", "市場、茶館、老街、村落和社區，旅行不一定每天都要趕景點。"]],
    emotionalLabel: "TRAVEL DEEPER INTO FUJIAN", emotionalTitle: "真正記住的，\n往往不是景點。", emotionalText: "可能是一頓飯，\n一句熟悉的鄉音，\n一座老房子，\n或是一段你原本不知道的家族故事。",
    serviceLabel: "TRAVEL MADE SIMPLE", serviceTitle: "你負責來福建，\n剩下的我們一起安排。", serviceIntro: "不用同時找司機、飯店、路線和在地體驗。告訴我們你想怎麼玩，我們把整段旅程串起來。", services: [["PRIVATE CAR", "私人用車", "機場接送、每日包車、城市之間的交通，依人數和路線安排合適車輛。"], ["STAYS", "住宿安排", "依預算、位置和旅行方式推薦住宿，不預設綁定固定飯店。"], ["PICKUP", "機場 / 高鐵接送", "廈門機場、高鐵站及主要交通節點，均可依最終行程安排接送。"], ["LOCAL EXPERIENCES", "在地體驗", "美食、文化、村落、茶、尋根等體驗，都可以加入私人行程。"], ["TRIP SUPPORT", "行程協助", "從出發前規劃到旅行中的調整，都有真人可以聯絡。"]],
    aboutLabel: "關於我們 ◆ ABOUT TRIPFUJIAN", aboutTitle: "我們就在福建。", aboutText: "我們是一支位於廈門的在地旅行團隊。相比把你塞進固定團，我們更願意先知道你和誰來、喜歡什麼、希望走快一點還是慢一點，再一起把旅程安排出來。", trustPoints: [["福建在地", "熟悉福建路線、交通和在地體驗。"], ["真人溝通", "旅行前後都有真實顧問聯絡。"], ["行程透明", "提前確認路線、服務與費用。"]],
    faqLabel: "出發前常見問題 ◆ FAQ", plannerLabel: "開始你的旅程 ◆ PLAN YOUR TRIP", plannerTitle: "先告訴我們，\n你想怎麼認識福建。", plannerText: "不需要馬上決定路線，也不需要立即付款。告訴我們日期、人數和想去的地方，我們先幫你整理旅行方向。", plannerCta: "開始規劃我的福建旅行",
  },
  en: {
    heroLabel: "FUJIAN · CHINA", heroTitle: "Your first Fujian trip,\nplanned with Fujian locals.", heroText: "From Xiamen's coast to Quanzhou's old city, tulou villages and Pingtan's shoreline, we shape a private journey around your family, time and pace.", primary: "Start planning my Fujian trip", secondary: "Talk to an advisor on WhatsApp", heroNote: "Private planning · Private transport · Flexible pace · No shopping stops by default",
    journeyLabel: "CURATED JOURNEYS", journeyTitle: "A thoughtful first journey\nthrough Fujian.", journeyIntro: "Not sure where to begin? Start with one of these routes for a first Fujian trip, then adjust it around your time and interests.", journeys: [["01", "Classic Fujian · 5 days", "Xiamen → Gulangyu → Fujian Tulou → Quanzhou", "FIRST TIME IN FUJIAN\nRecommended for a first visit", "A well-paced first introduction to Fujian.", "Begin by the sea in Xiamen, walk Gulangyu's old lanes, stay among the mountain tulou, then experience Minnan culture in Quanzhou. Five days cover the essentials without rushing.", "Gulangyu / Fujian Tulou / Quanzhou old city / Minnan food", "5 days · Private vehicle · Flexible itinerary", "View the 5-day journey"], ["02", "Mountains & coast · 7 days", "Xiamen → Quanzhou → Pingtan → Fujian Tulou", "COAST & CULTURE\nLandscapes and living heritage", "Take two more days to see Fujian's mountains and coast.", "Travel from Quanzhou's old city to Pingtan's shoreline, then into tulou country and mountain villages. For travellers who prefer to slow down and experience more than landmarks.", "Quanzhou old city / Pingtan coast / Fujian Tulou / Local life", "7 days · Private vehicle · Travel at your pace", "View the 7-day journey"], ["03", "Private family Fujian · 6 days", "Xiamen → Gulangyu → Fujian Tulou → Quanzhou", "FAMILY PRIVATE TOUR\nFamily travel", "Fujian can feel easy with parents and children.", "Fewer long travel days and hotel changes, with each day adjusted around older relatives and children. We plan the vehicle, transfers and stays together so the family can focus on the trip.", "Family friendly / Private vehicle / Less rushing / Flexible itinerary", "6 days · Designed for families · Adjustable by age", "View the family journey"]], journeyFooterTitle: "Need a different route?", journeyFooterText: "Tell us how many days you have and who is travelling. We can design your Fujian trip from the beginning.", journeyFooterCta: "Plan my Fujian trip free",
    destinationLabel: "EXPLORE FUJIAN", destinationTitle: "There is more to Fujian\nthan Xiamen.", destinationIntro: "Islands, old cities, tulou, tea country and villages—each side of Fujian suits a different way of travelling.", destinations: [["XIAMEN", "Xiamen", "Island streets, old neighbourhoods and easy coastal life", "Coastal city · Gulangyu · Food"], ["QUANZHOU", "Quanzhou", "See living Minnan culture in the old city", "World Heritage · Minnan culture · Old city"], ["FUJIAN TULOU", "Fujian Tulou", "Stay in the valley and discover another side of Fujian", "World Heritage · Villages · Hakka culture"], ["PINGTAN", "Pingtan", "Follow the coast road towards Fujian's bluest sea", "Island · Coast · Sunset"], ["WUYI MOUNTAIN", "Wuyi Mountain", "Mountain scenery, tea country and a few slower days", "Landscape · Wuyi rock tea · Hiking"]], explore: "Explore ", destinationCta: "Explore Fujian destinations",
    experienceLabel: "BEYOND SIGHTSEEING", experienceTitle: "Fujian is more than\na list of sights.", experienceIntro: "Some of Fujian lives in a meal, an old house,\na familiar accent and the rhythm of local life.", rootsMeta: "01", rootsLabel: "ROOTS JOURNEY", rootsName: "Fujian roots journey", rootsTitle: "Return to where the story began.", rootsText: "If your family comes from Fujian, we can help shape a homecoming and roots journey around ancestral places, surnames and the clues you already have.", rootsKeywords: "Ancestral villages · Ancestral halls · Family clues · Homecoming visits", rootsCta: "Explore Fujian roots journeys", experiences: [["FUJIAN FOOD", "Fujian flavours", "Go beyond popular restaurants and discover Fujian through snacks, tea and the tables where local people gather."], ["MINNAN CULTURE", "Minnan culture", "From Quanzhou's old city, temples and red-brick houses to local beliefs, see how Minnan culture lives today."], ["TRADITIONAL DRESS", "Traditional dress", "Discover the clothing and aesthetics of different parts of Fujian, with experiences and photography arranged around your interests."], ["LOCAL LIFE", "Local life", "Markets, teahouses, old streets, villages and neighbourhoods—travel does not have to mean rushing between sights."]],
    emotionalLabel: "TRAVEL DEEPER INTO FUJIAN", emotionalTitle: "What stays with you\nis rarely just a landmark.", emotionalText: "It might be a meal,\na familiar accent,\nan old house,\nor a family story you never knew.",
    serviceLabel: "TRAVEL MADE SIMPLE", serviceTitle: "Come to Fujian.\nWe will arrange the journey together.", serviceIntro: "You do not need to find a driver, hotel, route and local experiences separately. Tell us how you want to travel, and we will connect the whole journey.", services: [["PRIVATE CAR", "Private vehicle", "Airport transfers, daily private transport and intercity travel, with a suitable vehicle arranged for your group and route."], ["STAYS", "Stay planning", "Accommodation suggestions based on budget, location and travel style, without tying you to a fixed hotel."], ["PICKUP", "Airport / rail transfers", "Transfers can be arranged around your final itinerary at Xiamen Airport, railway stations and major transport points."], ["LOCAL EXPERIENCES", "Local experiences", "Food, culture, villages, tea and roots experiences can all become part of your private itinerary."], ["TRIP SUPPORT", "Trip support", "A real person stays available from planning before departure through adjustments during the journey."]],
    aboutLabel: "关于我们 ◆ ABOUT TRIPFUJIAN", aboutTitle: "We are here in Fujian.", aboutText: "We are a local travel team based in Xiamen. Instead of placing you into a fixed group tour, we first learn who you are travelling with, what you enjoy and whether you prefer a faster or slower pace—then plan the journey together.", trustPoints: [["Fujian local", "Familiar with local routes, transport and experiences."], ["Real communication", "A real advisor stays in touch before and during travel."], ["Clear itinerary", "Routes, services and costs are confirmed in advance."]],
    faqLabel: "出发前常见问题 ◆ FAQ", plannerLabel: "开始你的旅程 ◆ PLAN YOUR TRIP", plannerTitle: "Tell us how you want\nto experience Fujian.", plannerText: "You do not need to choose a route or pay now. Share your dates, group and places of interest, and we will first organise a clear travel direction.", plannerCta: "Start planning my Fujian trip",
  },
} as const;

const C = {
  "zh-CN": {
    heroTitle: "用你的方式，\n发现福建", heroLead: "第一次来福建？\n让福建本地人帮你规划。", heroText: "从厦门、泉州到福建土楼、平潭和武夷山，根据旅行日期、人数和旅行方式，为你设计私人定制旅程。", primary: "免费规划我的福建旅行", secondary: "WhatsApp 联系旅行顾问",
    strip: ["福建本地团队", "私人定制", "无强制购物", "专车出行", "行程灵活调整"],
    routeTitle: "第一次来福建，可以这样玩", routeIntro: "从一个清晰的旅行方向开始，再按日期、同行成员和节奏调整。", routes: [
      ["福建经典5天", "厦门 → 鼓浪屿 → 福建土楼 → 泉州", "把福建最有代表性的海岛、土楼和古城放进一次旅程。", "第一次来福建"],
      ["福建深度7天", "厦门 → 土楼 → 泉州 → 平潭", "多一点时间走进闽南文化，也感受福建海岸的开阔。", "文化与海岸"],
      ["福建家庭私人游6天", "厦门 → 鼓浪屿 → 土楼 → 泉州", "为家庭、长辈和孩子保留更从容的移动与休息节奏。", "家庭小团"],
    ], viewTrip: "查看行程", noRoute: "没有适合你的？", tellUs: "告诉我们你想怎么玩",
    destinationTitle: "一个福建，不止一种旅行", destinations: [["厦门", "沿着海岸与岛屿，慢慢认识福建的第一站。"], ["泉州", "在古城街巷里看见海丝文化与日常生活。"], ["福建土楼", "走进山谷村落与世代生活的圆形家园。"], ["平潭", "海风、公路与开阔海岸组成轻快的一天。"], ["武夷山", "在山水、茶香与自然步道之间放慢脚步。"]], explore: "探索目的地", photoPending: "真实图片待提供",
    experienceTitle: "不只是看景点，真正走进福建", experiences: [["福建寻根", "从祖籍线索出发，寻找家族与地方的连接。"], ["福建味道", "从市场、小吃到一桌当地菜，认识福建的日常。"], ["闽南文化", "读懂古城、宗祠、建筑与海洋文化留下的痕迹。"], ["传统服饰", "在合适的历史场景中体验服饰与旅拍。"], ["当地生活", "走进街巷、社区与仍在发生的地方传统。"]], experienceCta: "探索福建文化体验",
    journeyTitle: "你负责来到福建，剩下的我们帮你安排", journeyIntro: "TripFujian 协调的是整段旅程，不是把酒店、车辆和向导分开销售。", journey: ["抵达", "机场/高铁接送", "私人用车", "酒店入住", "当地体验", "旅途支持", "送机/送站"],
    trustTitle: "为什么放心把福建旅行交给我们？", trust: ["福建本地团队", "真人旅行顾问沟通", "私人定制", "行程和费用透明", "不默认安排购物", "家庭、老人、儿童行程可调整", "真实公司主体"], company: "与君游（厦门）国际旅游有限公司", address: "厦门市集美区杏林湾路474号2606单元",
    teamTitle: "认识你的福建本地旅行团队", teamText: "团队位于厦门，熟悉福建旅行的路线、交通、住宿与当地体验，并帮助海外游客把这些安排衔接起来。", teamPending: "真实团队照片待提供", teamCta: "认识我们",
    faqTitle: "第一次来福建，常见的问题", faqs: [["不会中文怎么办？", "可以先通过网站提交需求，并选择常用联系方式。实际沟通语言与服务安排会在方案确认时说明。"], ["外国游客在中国如何付款？", "支付方式和可用范围可能变化。旅行顾问会根据出行时间提供准备建议，最终以相关服务当时公布的信息为准。"], ["可以机场接机吗？", "可以在行程方案中提出机场或高铁站接送需求，车辆与时间以最终确认方案为准。"], ["可以 WhatsApp 联系吗？", "可以在咨询表单中选择 WhatsApp，并留下你的号码；顾问会通过你选择的方式联系。"], ["带老人和孩子适合吗？", "可以根据步行能力、休息需求和儿童年龄调整每天的节奏与用车安排。"], ["福建推荐玩几天？", "第一次来福建可以先从5至7天的路线寻找灵感，再根据航班、兴趣与体力调整。"], ["签证和入境政策如何确认？", "政策可能变化。出发前请以相关政府、使领馆及承运方发布的最新信息为准，我们不会在网站写死具体政策。"]],
    plannerTitle: "开始规划你的福建旅行", plannerIntro: "六个简单步骤，帮助旅行顾问先了解你的时间、同行成员和兴趣。", steps: ["什么时候来？", "同行人数", "旅行天数", "福建目的地", "兴趣偏好", "联系方式"], date: "预计出发月份", adults: "成人", children: "儿童", days: "计划旅行几天？", dayOptions: ["3–5天", "6–8天", "9天以上", "还没决定"], destinationOptions: ["厦门", "泉州", "福建土楼", "平潭", "武夷山", "请顾问建议"], interestOptions: ["美食", "文化", "自然", "摄影", "亲子", "慢旅行", "寻根"], contactMethod: "希望如何联系？", contactOptions: ["WhatsApp", "Email", "WeChat"], name: "怎么称呼你？", contact: "联系方式", email: "电子邮箱（选填）", notes: "还有什么想告诉我们？（选填）", consent: "我同意资料仅用于本次旅行咨询，并已阅读隐私政策。", privacy: "隐私政策", back: "上一步", next: "下一步", submit: "免费获取我的福建旅行建议", noBooking: "提交需求不等于下单，无需立即付款。", choose: "请至少选择一项。", sending: "正在提交…", success: "已收到你的需求，我们会通过你选择的方式联系你。", fallback: "暂时无法提交，请稍后重试或通过邮箱联系我们。",
  },
  "zh-TW": {
    heroTitle: "用你的方式，\n發現福建", heroLead: "第一次來福建？\n讓福建在地人幫你規劃。", heroText: "從廈門、泉州到福建土樓、平潭與武夷山，依旅行日期、人數和旅行方式，為你設計私人訂製旅程。", primary: "免費規劃我的福建旅行", secondary: "WhatsApp 聯絡旅行顧問",
    strip: ["福建在地團隊", "私人訂製", "無強制購物", "專車出行", "行程彈性調整"],
    routeTitle: "第一次來福建，可以這樣玩", routeIntro: "先從清楚的旅行方向開始，再依日期、同行成員與節奏調整。", routes: [["福建經典5天", "廈門 → 鼓浪嶼 → 福建土樓 → 泉州", "把福建最具代表性的海島、土樓和古城放進一次旅程。", "第一次來福建"], ["福建深度7天", "廈門 → 土樓 → 泉州 → 平潭", "多一點時間走進閩南文化，也感受福建海岸的開闊。", "文化與海岸"], ["福建家庭私人遊6天", "廈門 → 鼓浪嶼 → 土樓 → 泉州", "為家庭、長輩和孩子保留更從容的移動與休息節奏。", "家庭小團"]], viewTrip: "查看行程", noRoute: "沒有適合你的？", tellUs: "告訴我們你想怎麼玩",
    destinationTitle: "一個福建，不只一種旅行", destinations: [["廈門", "沿著海岸與島嶼，慢慢認識福建的第一站。"], ["泉州", "在古城街巷裡看見海絲文化與日常生活。"], ["福建土樓", "走進山谷村落與世代生活的圓形家園。"], ["平潭", "海風、公路與開闊海岸組成輕快的一天。"], ["武夷山", "在山水、茶香與自然步道之間放慢腳步。"]], explore: "探索目的地", photoPending: "真實圖片待提供",
    experienceTitle: "不只是看景點，真正走進福建", experiences: [["福建尋根", "從祖籍線索出發，尋找家族與地方的連結。"], ["福建味道", "從市場、小吃到一桌在地菜，認識福建的日常。"], ["閩南文化", "讀懂古城、宗祠、建築與海洋文化留下的痕跡。"], ["傳統服飾", "在合適的歷史場景中體驗服飾與旅拍。"], ["在地生活", "走進街巷、社區與仍在發生的地方傳統。"]], experienceCta: "探索福建文化體驗",
    journeyTitle: "你負責來到福建，剩下的我們幫你安排", journeyIntro: "TripFujian 協調的是整段旅程，不是把飯店、車輛和嚮導分開銷售。", journey: ["抵達", "機場/高鐵接送", "私人用車", "飯店入住", "在地體驗", "旅途支援", "送機/送站"],
    trustTitle: "為什麼放心把福建旅行交給我們？", trust: ["福建在地團隊", "真人旅行顧問溝通", "私人訂製", "行程和費用透明", "不預設安排購物", "家庭、長輩、兒童行程可調整", "真實公司主體"], company: "與君游（廈門）國際旅遊有限公司", address: "廈門市集美區杏林灣路474號2606單元",
    teamTitle: "認識你的福建在地旅行團隊", teamText: "團隊位於廈門，熟悉福建旅行的路線、交通、住宿與在地體驗，並協助海外旅客把這些安排銜接起來。", teamPending: "真實團隊照片待提供", teamCta: "認識我們",
    faqTitle: "第一次來福建，常見的問題", faqs: [["不會中文怎麼辦？", "可以先透過網站提交需求，並選擇常用聯絡方式。實際溝通語言與服務安排會在方案確認時說明。"], ["外國旅客在中國如何付款？", "支付方式與可用範圍可能變化。旅行顧問會依出行時間提供準備建議，最終以相關服務當時公布的資訊為準。"], ["可以機場接機嗎？", "可以在行程方案中提出機場或高鐵站接送需求，車輛與時間以最終確認方案為準。"], ["可以用 WhatsApp 聯絡嗎？", "可以在諮詢表單中選擇 WhatsApp 並留下號碼；顧問會透過你選擇的方式聯絡。"], ["帶長輩和孩子適合嗎？", "可以依步行能力、休息需求和兒童年齡調整每天的節奏與用車安排。"], ["福建建議玩幾天？", "第一次來福建可先從5至7天的路線尋找靈感，再依航班、興趣與體力調整。"], ["簽證和入境政策如何確認？", "政策可能變化。出發前請以相關政府、使領館及承運方發布的最新資訊為準，我們不會在網站寫死具體政策。"]],
    plannerTitle: "開始規劃你的福建旅行", plannerIntro: "六個簡單步驟，幫助旅行顧問先了解你的時間、同行成員和興趣。", steps: ["什麼時候來？", "同行人數", "旅行天數", "福建目的地", "興趣偏好", "聯絡方式"], date: "預計出發月份", adults: "成人", children: "兒童", days: "計畫旅行幾天？", dayOptions: ["3–5天", "6–8天", "9天以上", "還沒決定"], destinationOptions: ["廈門", "泉州", "福建土樓", "平潭", "武夷山", "請顧問建議"], interestOptions: ["美食", "文化", "自然", "攝影", "親子", "慢旅行", "尋根"], contactMethod: "希望如何聯絡？", contactOptions: ["WhatsApp", "Email", "WeChat"], name: "怎麼稱呼你？", contact: "聯絡方式", email: "電子郵件（選填）", notes: "還有什麼想告訴我們？（選填）", consent: "我同意資料僅用於本次旅行諮詢，並已閱讀隱私政策。", privacy: "隱私政策", back: "上一步", next: "下一步", submit: "免費取得我的福建旅行建議", noBooking: "提交需求不等於下單，無需立即付款。", choose: "請至少選擇一項。", sending: "正在提交…", success: "已收到你的需求，我們會透過你選擇的方式聯絡你。", fallback: "暫時無法提交，請稍後重試或透過電郵聯絡我們。",
  },
  en: {
    heroTitle: "Discover Fujian,\nyour way", heroLead: "First time in Fujian?\nPlan it with a local team.", heroText: "From Xiamen and Quanzhou to the Fujian tulou, Pingtan and Wuyi Mountain, we shape a private trip around your dates, group and travel style.", primary: "Plan my Fujian trip free", secondary: "Talk to an advisor on WhatsApp",
    strip: ["Fujian-based team", "Private custom trips", "No forced shopping", "Private transport", "Flexible itinerary"],
    routeTitle: "Three ways to start your first Fujian trip", routeIntro: "Start with a clear route, then adjust it around your dates, group and preferred pace.", routes: [["Classic Fujian · 5 days", "Xiamen → Gulangyu → Fujian Tulou → Quanzhou", "See Fujian through its island streets, tulou villages and historic port city.", "First-time visit"], ["Fujian in depth · 7 days", "Xiamen → Tulou → Quanzhou → Pingtan", "Take more time for Minnan culture and the open landscapes of Fujian's coast.", "Culture and coast"], ["Private family Fujian · 6 days", "Xiamen → Gulangyu → Tulou → Quanzhou", "A more comfortable pace for families travelling with children or older relatives.", "Private family trip"]], viewTrip: "View itinerary", noRoute: "Not quite right?", tellUs: "Tell us how you want to travel",
    destinationTitle: "One province, many ways to travel", destinations: [["Xiamen", "Begin with island streets, sea views and an easy coastal pace."], ["Quanzhou", "Find maritime heritage and everyday life in the old city's lanes."], ["Fujian Tulou", "Enter mountain villages shaped around remarkable communal homes."], ["Pingtan", "Follow sea roads, wind and wide-open coastal scenery."], ["Wuyi Mountain", "Slow down among mountain paths, river scenery and tea country."]], explore: "Explore destination", photoPending: "Real photography needed",
    experienceTitle: "Go beyond the sights and into Fujian", experiences: [["Roots journeys", "Begin with family clues and reconnect with places tied to your ancestry."], ["Fujian flavours", "Discover everyday Fujian through markets, small eats and local tables."], ["Minnan culture", "Read stories held in old cities, ancestral halls and coastal architecture."], ["Traditional dress", "Experience traditional clothing and photography in an appropriate historic setting."], ["Local life", "Step into neighbourhoods, lanes and living traditions beyond the landmark list."]], experienceCta: "Explore Fujian experiences",
    journeyTitle: "Get to Fujian. We will help with the rest.", journeyIntro: "TripFujian coordinates the journey as a whole—not hotels, vehicles and guides as disconnected products.", journey: ["Arrival", "Airport or rail pickup", "Private vehicle", "Hotel check-in", "Local experiences", "On-trip support", "Departure transfer"],
    trustTitle: "Why entrust your Fujian trip to us?", trust: ["Fujian-based team", "A real travel advisor", "Private custom planning", "Clear itinerary and costs", "No shopping stops by default", "Pacing for families, seniors and children", "A registered company"], company: "Yujunyou (Xiamen) International Travel Co., Ltd.", address: "Unit 2606, No. 474 Xinglinwan Road, Jimei District, Xiamen, Fujian, China",
    teamTitle: "Meet your local Fujian travel team", teamText: "Our team is based in Xiamen. We help overseas visitors connect routes, transport, stays and local experiences across Fujian.", teamPending: "Real team photography needed", teamCta: "Meet the team",
    faqTitle: "Questions before your first Fujian trip", faqs: [["What if I do not speak Chinese?", "Start by sharing your needs and preferred contact method. Available communication and trip support will be explained before you confirm a plan."], ["How can international visitors pay in China?", "Payment access can change. Your advisor can share preparation guidance for your travel dates; always confirm with the relevant provider's current information."], ["Can you arrange airport pickup?", "Yes. Ask for an airport or railway transfer in your trip plan. The vehicle and timing are confirmed in the final proposal."], ["Can I use WhatsApp?", "Yes. Choose WhatsApp in the inquiry form and leave your number so an advisor can contact you there."], ["Can you plan for seniors and children?", "Yes. We can adjust walking, rest time and transport around the ages and mobility of your group."], ["How many days should I spend in Fujian?", "A five-to-seven-day route is a useful starting point for a first visit, then we adjust it around flights, interests and pace."], ["How should I confirm visa and entry rules?", "Rules can change. Check the latest government, embassy, consulate and carrier information before departure; we do not hard-code changing policies on this page."]],
    plannerTitle: "Start planning your Fujian trip", plannerIntro: "Six short steps give your advisor the dates, group and interests needed to begin.", steps: ["When are you coming?", "Who is travelling?", "Trip length", "Fujian destinations", "Interests", "Contact"], date: "Expected travel month", adults: "Adults", children: "Children", days: "How long would you like to travel?", dayOptions: ["3–5 days", "6–8 days", "9+ days", "Not decided"], destinationOptions: ["Xiamen", "Quanzhou", "Fujian Tulou", "Pingtan", "Wuyi Mountain", "Let the advisor suggest"], interestOptions: ["Food", "Culture", "Nature", "Photography", "Family", "Slow travel", "Roots journey"], contactMethod: "How should we contact you?", contactOptions: ["WhatsApp", "Email", "WeChat"], name: "Your name", contact: "Contact details", email: "Email address (optional)", notes: "Anything else we should know? (optional)", consent: "I agree that my details may be used for this travel inquiry and have read the Privacy Policy.", privacy: "Privacy Policy", back: "Back", next: "Continue", submit: "Get my free Fujian trip advice", noBooking: "Sending an inquiry is not a booking. No payment is required now.", choose: "Please choose at least one option.", sending: "Sending…", success: "We received your request and will contact you through your chosen method.", fallback: "We could not submit your request. Please try again or contact us by email.",
  },
} as const;

export default function LocalizedHome({ locale }: { locale: PublicLocale }) {
  const [step, setStep] = useState(1);
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  const [stepError, setStepError] = useState("");
  const formRef = useRef<HTMLFormElement>(null);
  const t = C[locale];
  const v = V1[locale];
  const root = locale === "en" ? "/en" : locale === "zh-TW" ? "/zh-tw" : "";
  const heroSecondary = locale === "en" ? "Talk with a travel advisor" : locale === "zh-TW" ? "和旅行顧問聊聊" : "和旅行顾问聊聊";
  const aboutCopy = locale === "en"
    ? { label: "LOCAL TEAM · REAL FUJIAN", text: "TripFujian is a local travel team from Fujian.\n\nWe know the routes, transport, stays and pace of travelling here, and want a first visit to feel less unfamiliar and more reassuring.\n\nWe do not put everyone into one fixed route. Tell us when you are coming, who is travelling and what you enjoy, then we will design the journey together.", points: [["01 Fujian local / LOCAL IN FUJIAN", "Familiar with Fujian's key destinations, transport and travel pace."], ["02 Real people / REAL PEOPLE", "A real person speaks with you from your first inquiry."], ["03 Clear itinerary / CLEAR ITINERARY", "Routes, stays, vehicles and related costs are explained when the plan is confirmed."], ["04 Made for you / MADE FOR YOU", "The itinerary can flex around your group, time, budget and interests."]], ctaTitle: "Planning your first trip with us?", ctaText: "It is normal to have questions when contacting a local Fujian travel team for the first time. Share roughly when you are coming, how many people are travelling and where you hope to go. We will first check whether the route makes sense—an inquiry does not commit you to booking.", cta: "Talk through my Fujian trip" }
    : locale === "zh-TW"
      ? { label: "LOCAL TEAM · REAL FUJIAN", text: "TripFujian 是一個來自福建的在地旅行團隊。\n\n我們熟悉這裡的路線、交通、住宿和旅行節奏，也希望讓第一次來到福建的人，少一點陌生，多一點安心。\n\n我們不希望把每個人塞進同一條固定路線。告訴我們什麼時候來、和誰一起、喜歡什麼，再一起把旅程設計出來。", points: [["01 福建在地 / LOCAL IN FUJIAN", "熟悉福建主要目的地、交通方式和旅行節奏。"], ["02 真人溝通 / REAL PEOPLE", "從第一次諮詢開始，由真人與你溝通旅行需求。"], ["03 行程透明 / CLEAR ITINERARY", "路線、住宿、車輛和相關費用，在確認方案時說明清楚。"], ["04 私人訂製 / MADE FOR YOU", "依人數、時間、預算和興趣調整行程。"]], ctaTitle: "第一次找我們旅行？", ctaText: "第一次聯絡一家福建在地旅行團隊，有疑問很正常。你可以先告訴我們大概什麼時候來、幾個人、想去哪些地方。我們先幫你看看路線是否合理，諮詢不代表必須預訂。", cta: "先聊聊我的福建旅行" }
      : { label: "LOCAL TEAM · REAL FUJIAN", text: "TripFujian 是一个来自福建的本地旅行团队。\n\n我们熟悉这里的路线、交通、住宿和旅行节奏，也希望让第一次来到福建的人，少一点陌生，多一点安心。\n\n我们不希望把每个人塞进同一条固定路线。告诉我们什么时候来、和谁一起、喜欢什么，再一起把旅程设计出来。", points: [["01 福建本地 / LOCAL IN FUJIAN", "熟悉福建主要目的地、交通方式和旅行节奏。"], ["02 真人沟通 / REAL PEOPLE", "从第一次咨询开始，由真人与你沟通旅行需求。"], ["03 行程透明 / CLEAR ITINERARY", "路线、住宿、车辆和相关费用，在确认方案时说明清楚。"], ["04 私人定制 / MADE FOR YOU", "根据人数、时间、预算和兴趣调整行程。"]], ctaTitle: "第一次找我们旅行？", ctaText: "第一次联系一家福建本地旅行团队，有疑问很正常。你可以先告诉我们大概什么时候来、几个人、想去哪些地方。我们先帮你看看路线是否合理，咨询不代表必须预订。", cta: "先聊聊我的福建旅行" };
  const faqItems = locale === "en"
    ? [["Can you redesign a route around my needs?", "Yes. Every route can be shaped around your dates, group, interests and pace."], ["Can you arrange a private trip for just two people?", "Yes. Private travel can be arranged for two people as well as families and small groups."], ["Can you arrange airport or railway-station transfers?", "Yes. Airport and high-speed rail transfers can be added to the confirmed itinerary."], ["Can I choose the hotel and vehicle myself?", "Yes. Hotels and vehicles can be discussed around your budget, route and preferences."], ["Is Fujian suitable for parents or children?", "Yes. We can adjust walking, rest time, transport and daily pace for older relatives and children."], ["Will there be shopping stops or forced spending?", "No shopping stops or forced purchases are arranged by default."], ["Can I ask for advice before my dates are fixed?", "Yes. An approximate month, trip length and group size are enough to begin a conversation."], ["How can visitors from Taiwan, Singapore or Malaysia contact you?", "Use the contact options shown in the planner: email or WeChat. We do not list an unconfirmed channel."]]
    : locale === "zh-TW"
      ? [["可以依我的需求重新設計路線嗎？", "可以，會依日期、同行成員、興趣與節奏調整私人行程。"], ["只有兩個人，也可以安排私人旅行嗎？", "可以，兩人也能安排私人旅程。"], ["可以安排機場或高鐵站接送嗎？", "可以，接送需求會放進最終確認的行程。"], ["飯店和車輛可以自己選擇嗎？", "可以，會依預算、路線與偏好一起溝通。"], ["帶長輩或孩子適合嗎？", "可以，能依長輩與孩子的步行、休息和移動需求調整節奏。"], ["會安排購物店或強制消費嗎？", "預設不安排購物店，也不強制消費。"], ["還沒確定日期，可以先諮詢嗎？", "可以，先提供大概月份、天數和人數即可開始諮詢。"], ["台灣、新加坡和馬來西亞旅客怎麼聯絡？", "可在 Planner 選擇 Email 或 WeChat；我們只展示目前確認可用的聯絡方式。"]]
      : [["可以根据我的需求重新设计路线吗？", "可以，会根据日期、同行成员、兴趣和节奏调整私人行程。"], ["只有两个人，也可以安排私人旅行吗？", "可以，两个人也能安排私人旅程。"], ["可以安排机场或高铁站接送吗？", "可以，接送需求会放进最终确认的行程。"], ["酒店和车辆可以自己选择吗？", "可以，会根据预算、路线和偏好一起沟通。"], ["带父母或孩子适合吗？", "可以，能根据老人和孩子的步行、休息和移动需求调整节奏。"], ["会安排购物店或强制消费吗？", "默认不安排购物店，也不强制消费。"], ["我还没确定日期，可以先咨询吗？", "可以，先提供大概月份、天数和人数即可开始咨询。"], ["台湾、新加坡和马来西亚游客怎么联系？", "可在 Planner 选择 Email 或 WeChat；我们只展示目前确认可用的联系方式。"]];
  const plannerCopy = locale === "en"
    ? { title: "Tell us how you\nwant to travel Fujian.", text: "You do not need to work out every detail at once. Tell us roughly when you are coming, how many people are travelling and where you hope to go. We can plan the rest together, step by step.", cta: "Plan my Fujian trip free", note: "Sending an inquiry does not mean booking. We will first understand your travel needs, then confirm the route and arrangements together." }
    : locale === "zh-TW"
      ? { title: "告訴我們，\n你想怎麼玩福建。", text: "不用一次想清楚所有細節。告訴我們大概什麼時候來、幾個人、想去哪裡，剩下的可以一起慢慢規劃。", cta: "免費規劃我的福建旅行", note: "提交諮詢不代表下單。我們會先了解你的旅行需求，再一起確認路線與安排。" }
      : { title: "告诉我们，\n你想怎么玩福建。", text: "不用一次想清楚所有细节。告诉我们大概什么时候来、几个人、想去哪里，剩下的可以一起慢慢规划。", cta: "免费规划我的福建旅行", note: "提交咨询不代表下单。我们会先了解你的旅行需求，再一起确认路线与安排。" };
  const lang = locale === "en" ? "en" : locale === "zh-TW" ? "zh-Hant" : "zh-Hans";
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);

  function nextStep() {
    const panel = formRef.current?.querySelector<HTMLElement>(`[data-step="${step}"]`);
    if (!panel) return;
    setStepError("");
    const controls = Array.from(panel.querySelectorAll("input,select,textarea")) as Array<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>;
    for (const control of controls) if (!control.checkValidity()) { control.reportValidity(); return; }
    if ((step === 4 || step === 5) && !controls.some(control => control instanceof HTMLInputElement && control.type === "checkbox" && control.checked)) { setStepError(t.choose); return; }
    setStep(value => Math.min(6, value + 1));
  }

  async function submitInquiry(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const element = event.currentTarget;
    const form = new FormData(element);
    const destinations = form.getAll("destinations").map(String).join(" · ");
    const interests = form.getAll("interests").map(String).join(" · ");
    const notes = [`${locale === "en" ? "Children" : locale === "zh-TW" ? "兒童" : "儿童"}: ${form.get("children") || "0"}`, `${locale === "en" ? "Interests" : locale === "zh-TW" ? "興趣" : "兴趣"}: ${interests}`, String(form.get("notes") || "").trim()].filter(Boolean).join(" | ");
    const contact = `${form.get("contactMethod")}: ${form.get("contact")}${form.get("email") ? ` | Email ${form.get("email")}` : ""}`;
    const payload = { name: form.get("name"), contact, destinations, travelDate: form.get("date"), days: form.get("days"), adults: form.get("adults"), notes, source: locale, website: form.get("website"), privacyConsent: form.get("privacyConsent") === "on" };
    setStatus("sending"); setMessage(t.sending);
    try {
      const response = await fetch("/api/inquiries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json().catch(() => ({})) as { error?: string };
      if (!response.ok) throw new Error(result.error || t.fallback);
      element.reset(); setStep(1); setStatus("success"); setMessage(t.success);
    } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : t.fallback); }
  }

  return <main className="localized-page tripfujian-home" lang={lang}>
    <section className="tf-hero">
      <picture className="tf-hero-picture"><source media="(max-width:680px)" srcSet="/route-tulou-natural-v3.webp"/><img src="/trip-zhangzhou-tulou-hero-v2.webp" alt={locale === "en" ? "Inside a circular Fujian tulou surrounded by mountain scenery" : locale === "zh-TW" ? "福建山區環形土樓內部景觀" : "福建山区环形土楼内部景观"} fetchPriority="high"/></picture><div className="tf-hero-shade"/>
      <div className="shell tf-hero-content"><p className="tf-eyebrow">{v.heroLabel}</p><h1>{v.heroTitle.split("\n").map(line => <span key={line}>{line}</span>)}</h1><p className="tf-hero-text">{v.heroText}</p><div className="tf-hero-actions"><a className="tf-button tf-button-primary" href="#trip-planner">{v.primary} →</a><a className="tf-hero-secondary" href="#trip-planner" onClick={() => setStep(6)}>{heroSecondary} →</a></div><p className="tf-hero-note">{v.heroNote}</p></div>
    </section>

    <section className="tf-section shell tf-routes" id="trips"><header className="tf-v1-heading"><p className="tf-section-label">{v.journeyLabel}</p><h2>{v.journeyTitle.split("\n").map(line => <span key={line}>{line}</span>)}</h2><p className="tf-section-intro">{v.journeyIntro}</p></header><div className="tf-route-editorial">{v.journeys.map((route, index) => <article className="tf-route-story" key={route[0]}><div className="tf-route-media"><Image src={images.routes[index]} alt={route[1]} fill sizes="(max-width:760px) 100vw,60vw" unoptimized/></div><div className="tf-route-copy"><span className="tf-route-number">{route[0]}</span><p className="tf-route-tag">{route[3].split("\n").map(line => <span key={line}>{line}</span>)}</p><h3>{route[1]}</h3><p className="tf-route-path">{route[2]}</p><h4>{route[4]}</h4><p className="tf-route-description">{route[5]}</p><p className="tf-route-highlights">{route[6]}</p><p className="tf-route-meta">{route[7]}</p><a href={`${root}/trips`}>{route[8]} →</a></div></article>)}</div><div className="tf-route-footer-cta"><div><h3>{v.journeyFooterTitle}</h3><p>{v.journeyFooterText}</p></div><a className="tf-button tf-button-primary" href="#trip-planner">{v.journeyFooterCta} →</a></div></section>

    <section className="tf-section tf-destinations"><div className="shell"><header className="tf-v1-heading"><p className="tf-section-label">{v.destinationLabel}</p><h2>{v.destinationTitle.split("\n").map(line => <span key={line}>{line}</span>)}</h2><p className="tf-section-intro">{v.destinationIntro}</p></header><div className="tf-destination-grid">{v.destinations.map((destination, index) => <a className={`tf-destination-card${images.destinations[index] ? "" : " is-texture"}`} href={`${root}/trips`} aria-label={`${v.explore}${destination[1]}`} key={destination[0]}>{images.destinations[index] && <Image src={images.destinations[index]} alt={destination[1]} fill sizes="(max-width:760px) 100vw,60vw" unoptimized/>}<div className="tf-destination-shade"/><div className="tf-destination-copy"><span>{destination[0]}</span><h3>{destination[1]}</h3><p>{destination[2]}</p><small>{destination[3]}</small><span className="tf-destination-action">{v.explore}{destination[1]} →</span></div></a>)}</div><div className="tf-destination-footer"><a href={`${root}/trips`}>{v.destinationCta} →</a></div></div></section>

    <section className="tf-section shell tf-experiences"><header className="tf-v1-heading"><p className="tf-section-label">{v.experienceLabel}</p><h2>{v.experienceTitle.split("\n").map(line => <span key={line}>{line}</span>)}</h2><p className="tf-section-intro">{v.experienceIntro.split("\n").map(line => <span key={line}>{line}</span>)}</p></header><article className="tf-roots-feature"><div className="tf-roots-media"><Image src={images.experiences[0]} alt={locale === "en" ? "A traditional Fujian tulou connected with family roots" : "福建土楼与寻根旅行"} fill sizes="(max-width:760px) 100vw,58vw" unoptimized/></div><div className="tf-roots-copy"><span className="tf-roots-number">{v.rootsMeta}</span><p className="tf-roots-label">{v.rootsLabel}</p><h3 className="tf-roots-name">{v.rootsName}</h3><h4>{v.rootsTitle}</h4><p className="tf-roots-description">{v.rootsText}</p><p className="tf-roots-keywords">{v.rootsKeywords}</p><a href={`${root}/experiences`}>{v.rootsCta} →</a></div></article><div className="tf-experience-grid">{v.experiences.map((experience, index) => <article key={experience[0]}><div className="tf-experience-media"><Image src={images.experiences[index + 1]} alt={experience[1]} fill sizes="(max-width:760px) 100vw,25vw" unoptimized/></div><span>{String(index + 2).padStart(2, "0")}</span><p className="tf-experience-label">{experience[0]}</p><h3>{experience[1]}</h3><p className="tf-experience-description">{experience[2]}</p></article>)}</div></section>

    <section className="tf-emotional"><Image src="/trip-quanzhou-xunpu.webp" alt={locale === "en" ? "Local life in Quanzhou, Fujian" : locale === "zh-TW" ? "福建泉州在地生活場景" : "福建泉州当地生活场景"} fill sizes="100vw" unoptimized/><div className="tf-emotional-shade"/><div className="shell"><p className="tf-emotional-label">{v.emotionalLabel}</p><h2>{v.emotionalTitle.split("\n").map(line => <span key={line}>{line}</span>)}</h2><p className="tf-emotional-text">{v.emotionalText.split("\n").map(line => <span key={line}>{line}</span>)}</p></div></section>

    <section className="tf-section shell tf-services"><header className="tf-v1-heading"><p className="tf-section-label">{v.serviceLabel}</p><h2>{v.serviceTitle.split("\n").map(line => <span key={line}>{line}</span>)}</h2><p className="tf-section-intro">{v.serviceIntro}</p></header><div className="tf-service-list">{v.services.map((service, index) => <article key={service[0]}><span>{String(index + 1).padStart(2, "0")}</span><p className="tf-service-label">{service[0]}</p><h3>{service[1]}</h3><p className="tf-service-description">{service[2]}</p></article>)}</div></section>

    <section className="tf-section tf-about"><div className="shell tf-about-layout"><div className="tf-about-media"><Image src="/trip-zhangzhou-yunshuiyao.webp" alt={locale === "en" ? "A Fujian village landscape" : locale === "zh-TW" ? "福建村落環境" : "福建村落环境"} fill sizes="(max-width:760px) 100vw,52vw" unoptimized/></div><div className="tf-about-copy"><p className="tf-section-label">{aboutCopy.label}</p><h2>{v.aboutTitle}</h2><p className="tf-about-lead">{aboutCopy.text}</p><div className="tf-trust-points">{aboutCopy.points.map(point => <article key={point[0]}><h3>{point[0]}</h3><p>{point[1]}</p></article>)}</div><div className="tf-about-company"><strong>TripFujian <small>by Yujunyou Travel</small></strong><span>{t.company}</span><span>{t.address}</span></div><div className="tf-about-cta"><h3>{aboutCopy.ctaTitle}</h3><p>{aboutCopy.ctaText}</p><a className="tf-text-link" href="#trip-planner">{aboutCopy.cta} →</a></div></div></div></section>

    <section className="tf-section shell tf-faq"><header className="tf-v1-heading"><p className="tf-section-label">{v.faqLabel}</p><h2>{t.faqTitle}</h2></header><div className="tf-faq-list">{faqItems.map((item, index) => <details key={item[0]}><summary><span>{String(index + 1).padStart(2, "0")}</span>{item[0]}</summary><p>{item[1]}</p></details>)}</div></section>

    <section className="tf-section tf-planner" id="trip-planner"><div className="shell tf-planner-layout"><div className="tf-planner-intro"><span>{v.plannerLabel}</span><h2>{plannerCopy.title.split("\n").map(line => <b key={line}>{line}</b>)}</h2><p>{plannerCopy.text}</p><a className="tf-planner-jump" href="#trip-planner-form">{plannerCopy.cta} →</a><ol>{t.steps.map((item, index) => <li className={step === index + 1 ? "active" : step > index + 1 ? "complete" : ""} key={item}><b>{index + 1}</b>{item}</li>)}</ol></div>
      <form ref={formRef} className="tf-planner-form" id="trip-planner-form" onSubmit={submitInquiry}><div className="tf-planner-progress"><span>{step} / 6</span><i style={{ width: `${step / 6 * 100}%` }}/></div>
        <fieldset data-step="1" hidden={step !== 1}><legend>{t.steps[0]}</legend><label>{t.date}<input name="date" type="month" required/></label></fieldset>
        <fieldset data-step="2" hidden={step !== 2}><legend>{t.steps[1]}</legend><div className="tf-field-row"><label>{t.adults}<input name="adults" type="number" min="1" defaultValue="2" required/></label><label>{t.children}<input name="children" type="number" min="0" defaultValue="0" required/></label></div></fieldset>
        <fieldset data-step="3" hidden={step !== 3}><legend>{t.steps[2]}</legend><label>{t.days}<select name="days" defaultValue="" required><option value="" disabled>—</option>{t.dayOptions.map(option => <option key={option}>{option}</option>)}</select></label></fieldset>
        <fieldset data-step="4" hidden={step !== 4}><legend>{t.steps[3]}</legend><div className="tf-choice-grid">{t.destinationOptions.map(option => <label key={option}><input type="checkbox" name="destinations" value={option}/><span>{option}</span></label>)}</div></fieldset>
        <fieldset data-step="5" hidden={step !== 5}><legend>{t.steps[4]}</legend><div className="tf-choice-grid">{t.interestOptions.map(option => <label key={option}><input type="checkbox" name="interests" value={option}/><span>{option}</span></label>)}</div></fieldset>
        <fieldset data-step="6" hidden={step !== 6}><legend>{t.steps[5]}</legend><label>{t.name}<input name="name" required/></label><label>{t.contactMethod}<select name="contactMethod" defaultValue="WhatsApp" required>{t.contactOptions.map(option => <option key={option}>{option}</option>)}</select></label><label>{t.contact}<input name="contact" required/></label><label>{t.email}<input name="email" type="email"/></label><label>{t.notes}<textarea name="notes" rows={3}/></label><label className="tf-consent"><input type="checkbox" name="privacyConsent" required/><span>{t.consent} <a href={`${root}/privacy`} target="_blank" rel="noreferrer">{t.privacy}</a></span></label><label className="form-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label></fieldset>
        {stepError && <p className="tf-planner-error" role="alert">{stepError}</p>}<div className="tf-planner-actions">{step > 1 && <button type="button" className="tf-button tf-button-back" onClick={() => { setStepError(""); setStep(value => value - 1); }}>{t.back}</button>}{step < 6 ? <button type="button" className="tf-button tf-button-primary" onClick={nextStep}>{t.next} →</button> : <button type="submit" className="tf-button tf-button-primary" disabled={status === "sending"}>{status === "sending" ? t.sending : t.submit}</button>}</div><p className="tf-no-booking">{plannerCopy.note}</p><p className={`tf-form-status ${status}`} role="status" aria-live="polite">{message}</p>
      </form>
    </div></section>
    <a className="tf-mobile-cta" href="#trip-planner">{v.primary}<span>→</span></a>
  </main>;
}
