import Image from "next/image";
import type { PublicLocale } from "./localized-home";
import styles from "./hotels/page.module.css";

type Hotel = { city: string; name: string; brand: string; detail: string };
const photos = ["/hotel-mandarin-oriental-shenzhen-official-v1.jpg", "/hotel-four-seasons-guangzhou-official-v1.jpg", "/hotel-interior-unbranded-official-v1.jpg"];

const localized = {
  "zh-CN": {
    eyebrow:"福建住宿安排", title:"不是只选五星，\n而是选得合适。", intro:"五星酒店用于展示我们的协调能力，并不代表客户只能选择五星。根据预算、路线和旅行方式，我们可安排五星、四星、连锁酒店、度假酒店、精品民宿及不同房型，全国住宿也可协助协调。", action:"咨询住宿安排",
    proof:["五星与高端酒店资源","四星・连锁・精品住宿","民宿・度假酒店・多种房型"], photoAlt:"高品质酒店空间实景",
    choiceLabel:"按需求来选", choiceTitle:"酒店类型和房型，都由客户需求决定。", choices:[["高端酒店","用于重要接待、纪念日或重视完整服务的行程。"],["四星与连锁","兼顾位置、稳定性和预算，适合多数多日路线。"],["度假与民宿","海岛、古城、茶山与乡村停留，可选择更有在地感的住宿。"],["房型与配置","大床、双床、家庭房、套房、加床、连通房及早餐逐项确认。"]],
    hotelLabel:"福建多城高端酒店参考", hotelTitle:"用代表性酒店，说明我们能协调到什么程度。", hotelIntro:"以下以福建多个城市的高端酒店为例，主要用于展示资源和协调能力。它们不是固定套餐，也不会限制客户选择其他星级、品牌或民宿。",
    hotels:[
      {city:"福州",name:"福州香格里拉大酒店",brand:"SHANGRI-LA",detail:"市中心停留参考，可衔接三坊七巷与市区行程。"},{city:"福州",name:"福州泰禾凯宾斯基酒店",brand:"KEMPINSKI",detail:"东二环区域的高端城市酒店参考。"},{city:"福州",name:"福州悦华酒店",brand:"C&D HOTELS",detail:"本地高端品牌参考，适合城市与周边路线。"},{city:"厦门",name:"厦门华尔道夫酒店",brand:"WALDORF ASTORIA",detail:"市中心高端住宿参考，可连接主要城区。"},{city:"厦门",name:"厦门康莱德酒店",brand:"CONRAD",detail:"思明滨海区域参考，适合城市景观行程。"},{city:"厦门",name:"厦门W酒店",brand:"W HOTELS",detail:"东部商务区的现代高端住宿参考。"},{city:"厦门",name:"厦门海悦山庄酒店",brand:"C&D HOTELS",detail:"环岛路度假住宿参考，适合家庭与休闲停留。"},{city:"泉州",name:"泉州泰禾洲际酒店",brand:"INTERCONTINENTAL",detail:"东海片区参考，可衔接古城与蟳埔路线。"},{city:"泉州",name:"泉州悦华酒店",brand:"C&D HOTELS",detail:"本地高端城市酒店参考，便于多点用车。"},{city:"莆田",name:"莆田香格里拉",brand:"SHANGRI-LA",detail:"绶溪公园一带的高端住宿参考。"},{city:"莆田",name:"莆田悦华酒店",brand:"C&D HOTELS",detail:"适合莆田市区及湄洲岛路线前后衔接。"},{city:"武夷山",name:"武夷山悦华酒店",brand:"C&D RESORT",detail:"度假区住宿参考，可衔接景区主要入口。"},{city:"武夷山",name:"武夷山大红袍山庄",brand:"DAHONGPAO RESORT",detail:"山水度假型住宿参考，适合茶文化行程。"},{city:"漳州",name:"漳州东山悦华酒店",brand:"C&D HOTELS",detail:"东山岛度假住宿参考，适合海岛慢游。"},{city:"三明",name:"三明梅园国际大酒店",brand:"MEIYUAN",detail:"三明城市高端住宿参考，可衔接周边县市。"},{city:"龙岩",name:"连城清水天一温泉度假村",brand:"TIANYI RESORT",detail:"连城度假住宿参考，适合温泉与客家路线。"}
    ] as Hotel[],
    approachLabel:"我们怎么选", approachTitle:"先看行程，再决定住哪里。", approaches:[["01","位置优先","减少折返，让入住、游览和第二天出发自然衔接。"],["02","按人选房","结合老人、儿童、同行关系和行李，核对房型与床型。"],["03","逐项确认","写明酒店、房型、早餐、取消规则、价格与可订情况。"]],
    coverageLabel:"全国也可安排", coverage:["福建全域","北京・天津","上海・江浙","广州・深圳","成都・重庆","西安・华中","云南・贵州","海南及其他目的地"], note:"以上酒店仅作能力和住宿范围参考，不代表固定合作、固定星级套餐或实时房态。客户也可选择四星酒店、连锁酒店、精品民宿及其他住宿。最终酒店、房型、早餐、价格、权益与可订情况，以出行日期和确认方案为准。", ctaTitle:"告诉我们预算、路线和想住的感觉。", ctaText:"我们会同时给出位置、类型和房型建议，不会只发一张五星酒店名单。", cta:"填写定制需求"
  },
  "zh-TW": {
    eyebrow:"福建住宿安排", title:"不只選五星，\n而是選得合適。", intro:"五星飯店用於展示我們的協調能力，並不代表旅客只能選擇五星。依預算、路線與旅行方式，我們可安排五星、四星、連鎖飯店、度假飯店、精品民宿及不同房型，全國住宿亦可協助協調。", action:"諮詢住宿安排",
    proof:["五星與高端飯店資源","四星・連鎖・精品住宿","民宿・度假飯店・多種房型"], photoAlt:"高品質飯店空間實景",
    choiceLabel:"依需求選擇", choiceTitle:"飯店類型與房型，都由旅客需求決定。", choices:[["高端飯店","適合重要接待、紀念日或重視完整服務的行程。"],["四星與連鎖","兼顧位置、穩定性與預算，適合多數多日路線。"],["度假與民宿","海島、古城、茶山與鄉村停留，可選擇更有在地感的住宿。"],["房型與配置","大床、雙床、家庭房、套房、加床、連通房與早餐逐項確認。"]],
    hotelLabel:"福建多城高端飯店參考", hotelTitle:"以代表性飯店，說明我們可協調的範圍。", hotelIntro:"以下以福建多個城市的高端飯店為例，主要用於展示資源與協調能力。它們不是固定套裝，也不會限制旅客選擇其他星級、品牌或民宿。",
    hotels:[
      {city:"福州",name:"福州香格里拉大酒店",brand:"SHANGRI-LA",detail:"市中心住宿參考，可銜接三坊七巷與市區行程。"},{city:"福州",name:"福州泰禾凱賓斯基酒店",brand:"KEMPINSKI",detail:"東二環區域的高端城市飯店參考。"},{city:"福州",name:"福州悅華酒店",brand:"C&D HOTELS",detail:"本地高端品牌參考，適合市區與周邊路線。"},{city:"廈門",name:"廈門華爾道夫酒店",brand:"WALDORF ASTORIA",detail:"市中心高端住宿參考，可連接主要市區。"},{city:"廈門",name:"廈門康萊德酒店",brand:"CONRAD",detail:"思明濱海區域參考，適合城市景觀行程。"},{city:"廈門",name:"廈門W酒店",brand:"W HOTELS",detail:"東部商務區的現代高端住宿參考。"},{city:"廈門",name:"廈門海悅山莊酒店",brand:"C&D HOTELS",detail:"環島路度假住宿參考，適合家庭與休閒停留。"},{city:"泉州",name:"泉州泰禾洲際酒店",brand:"INTERCONTINENTAL",detail:"東海片區參考，可銜接古城與蟳埔路線。"},{city:"泉州",name:"泉州悅華酒店",brand:"C&D HOTELS",detail:"本地高端城市飯店參考，便於多點用車。"},{city:"莆田",name:"莆田香格里拉",brand:"SHANGRI-LA",detail:"綬溪公園一帶的高端住宿參考。"},{city:"莆田",name:"莆田悅華酒店",brand:"C&D HOTELS",detail:"適合莆田市區及湄洲島路線前後銜接。"},{city:"武夷山",name:"武夷山悅華酒店",brand:"C&D RESORT",detail:"度假區住宿參考，可銜接景區主要入口。"},{city:"武夷山",name:"武夷山大紅袍山莊",brand:"DAHONGPAO RESORT",detail:"山水度假型住宿參考，適合茶文化行程。"},{city:"漳州",name:"漳州東山悅華酒店",brand:"C&D HOTELS",detail:"東山島度假住宿參考，適合海島慢遊。"},{city:"三明",name:"三明梅園國際大酒店",brand:"MEIYUAN",detail:"三明市區高端住宿參考，可銜接周邊縣市。"},{city:"龍岩",name:"連城清水天一溫泉度假村",brand:"TIANYI RESORT",detail:"連城度假住宿參考，適合溫泉與客家路線。"}
    ] as Hotel[],
    approachLabel:"我們如何選", approachTitle:"先看行程，再決定住哪裡。", approaches:[["01","位置優先","減少折返，讓入住、遊覽與隔天出發自然銜接。"],["02","依人選房","結合長者、兒童、同行關係與行李，核對房型與床型。"],["03","逐項確認","寫明飯店、房型、早餐、取消規則、價格與可訂情況。"]],
    coverageLabel:"全國亦可安排", coverage:["福建全域","北京・天津","上海・江浙","廣州・深圳","成都・重慶","西安・華中","雲南・貴州","海南及其他目的地"], note:"以上飯店僅作能力與住宿範圍參考，不代表固定合作、固定星級套裝或即時房況。旅客亦可選擇四星飯店、連鎖飯店、精品民宿及其他住宿。最終飯店、房型、早餐、價格、權益與可訂情況，以旅行日期和確認方案為準。", ctaTitle:"告訴我們預算、路線與想住的感覺。", ctaText:"我們會同時提供位置、類型與房型建議，不會只給一張五星飯店名單。", cta:"填寫訂製需求"
  },
  en: {
    eyebrow:"Stays across Fujian", title:"Not always five-star.\nAlways the right fit.", intro:"Five-star hotels demonstrate the level we can coordinate; they are not the only choice. We can arrange five- and four-star hotels, trusted chains, resorts, boutique stays, homestays and different room types around the route and budget, in Fujian and across China.", action:"Ask about stays",
    proof:["Five-star and premium access","Four-star, chain and boutique stays","Homestays, resorts and room options"], photoAlt:"A real premium hotel interior",
    choiceLabel:"Chosen around you", choiceTitle:"The stay type and room should follow the traveller.", choices:[["Premium hotels","For important hosting, celebrations or travellers who value full service."],["Four-star and chains","A practical balance of location, consistency and budget."],["Resorts and homestays","More local character for islands, old towns, tea country and rural stays."],["Rooms and setup","King, twin, family, suite, extra bed, connecting rooms and breakfast confirmed clearly."]],
    hotelLabel:"Premium references across Fujian", hotelTitle:"Representative hotels show what we can coordinate.", hotelIntro:"These premium properties across Fujian illustrate our reach and coordination capability. They are not a fixed package and do not limit travellers to one category, brand or stay type.",
    hotels:[
      {city:"Fuzhou",name:"Shangri-La Fuzhou",brand:"SHANGRI-LA",detail:"A central reference for the historic quarter and city routes."},{city:"Fuzhou",name:"Kempinski Hotel Fuzhou",brand:"KEMPINSKI",detail:"A premium city reference in the East Second Ring area."},{city:"Fuzhou",name:"C&D Hotel Fuzhou",brand:"C&D HOTELS",detail:"A local premium brand for city and regional itineraries."},{city:"Xiamen",name:"Waldorf Astoria Xiamen",brand:"WALDORF ASTORIA",detail:"A premium central base for Xiamen city travel."},{city:"Xiamen",name:"Conrad Xiamen",brand:"CONRAD",detail:"A Siming waterfront reference with city and harbour views."},{city:"Xiamen",name:"W Xiamen",brand:"W HOTELS",detail:"A contemporary premium stay in the east business district."},{city:"Xiamen",name:"Seaview Resort Xiamen",brand:"C&D HOTELS",detail:"A Huandao Road resort option for families and slower stays."},{city:"Quanzhou",name:"InterContinental Quanzhou",brand:"INTERCONTINENTAL",detail:"A Donghai base for the old city and Xunpu routes."},{city:"Quanzhou",name:"C&D Hotel Quanzhou",brand:"C&D HOTELS",detail:"A local premium city reference for multi-stop days."},{city:"Putian",name:"Shangri-La Putian",brand:"SHANGRI-LA",detail:"A premium reference beside Shouxi Park."},{city:"Putian",name:"C&D Hotel Putian",brand:"C&D HOTELS",detail:"For Putian city and before or after Meizhou Island."},{city:"Wuyi Mountain",name:"C&D Resort Wuyi Mountain",brand:"C&D RESORT",detail:"A resort-area reference close to key scenic access."},{city:"Wuyi Mountain",name:"Dahongpao Resort",brand:"DAHONGPAO RESORT",detail:"A landscape resort reference for tea-focused journeys."},{city:"Zhangzhou",name:"Dongshan C&D Hotel",brand:"C&D HOTELS",detail:"An island resort reference for a slower coastal stay."},{city:"Sanming",name:"Sanming Meiyuan International Hotel",brand:"MEIYUAN",detail:"A premium city reference for wider Sanming routes."},{city:"Longyan",name:"Liancheng Qingshui Tianyi Hot Spring Resort",brand:"TIANYI RESORT",detail:"A resort reference for hot springs and Hakka routes."}
    ] as Hotel[],
    approachLabel:"How we choose", approachTitle:"Start with the itinerary, then choose the stay.", approaches:[["01","Location first","Reduce backtracking and connect arrival, visits and departure."],["02","Match the room","Consider ages, room sharing, luggage, beds and family needs."],["03","Confirm clearly","State the hotel, room, breakfast, cancellation terms, price and availability."]],
    coverageLabel:"Across China too", coverage:["Across Fujian","Beijing and Tianjin","Shanghai and Jiangnan","Guangzhou and Shenzhen","Chengdu and Chongqing","Xi'an and central China","Yunnan and Guizhou","Hainan and other destinations"], note:"The hotels above illustrate capability and accommodation range only. They do not represent fixed partnerships, a five-star-only package or live availability. Four-star hotels, chains, boutique homestays and other stays can also be arranged. The final property, room, breakfast, price, benefits and availability are subject to the travel date and confirmed plan.", ctaTitle:"Share the budget, route and kind of stay you prefer.", ctaText:"We recommend locations, categories and rooms—not just a list of five-star hotels.", cta:"Start planning"
  }
} as const;

export default function LocalizedHotelsPage({locale}:{locale:PublicLocale}) {
  const t=localized[locale]; const root=locale==="zh-TW"?"/zh-tw":locale==="en"?"/en":""; const lang=locale==="zh-TW"?"zh-Hant":locale==="en"?"en":"zh-Hans";
  return <main lang={lang} className={`standalone-info-page ${styles.page}`}>
    <section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div className={styles.heroCopy}><p className="overline">{t.eyebrow}</p><h1>{t.title.split("\n").map(line=><span key={line}>{line}</span>)}</h1><p>{t.intro}</p><a href={`${root}/plan`}>{t.action} <span aria-hidden="true">→</span></a></div><div className={styles.heroMedia}><Image src={photos[0]} alt={t.photoAlt} fill priority sizes="(max-width:760px) 100vw,52vw"/></div></div><div className={`shell ${styles.proof}`}>{t.proof.map(item=><span key={item}>{item}</span>)}</div></section>
    <section className={`shell ${styles.choice}`}><header><p className="overline">{t.choiceLabel}</p><h2>{t.choiceTitle}</h2></header><div>{t.choices.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={`shell ${styles.gallery}`}>{photos.slice(1).map(src=><figure key={src}><Image src={src} alt={t.photoAlt} fill sizes="(max-width:760px) 100vw,50vw"/></figure>)}</section>
    <section className={`shell ${styles.partners}`}><header className={styles.sectionHead}><div><p className="overline">{t.hotelLabel}</p><h2>{t.hotelTitle}</h2></div><p>{t.hotelIntro}</p></header><div className={styles.hotelGrid}>{t.hotels.map((hotel,index)=><article key={`${hotel.city}-${hotel.name}`}><div className={styles.brandStage}><span>{String(index+1).padStart(2,"0")}</span><strong>{hotel.brand}</strong></div><div className={styles.hotelMeta}><span>{hotel.city}</span><h3>{hotel.name}</h3><p>{hotel.detail}</p></div></article>)}</div><p className={styles.note}>{t.note}</p></section>
    <section className={styles.approach}><div className="shell"><header><p className="overline">{t.approachLabel}</p><h2>{t.approachTitle}</h2></header><div>{t.approaches.map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className={`shell ${styles.coverage}`}><p className="overline">{t.coverageLabel}</p><div>{t.coverage.map(item=><span key={item}>{item}</span>)}</div></section>
    <section className={styles.cta}><div className="shell"><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><a href={`${root}/plan`}>{t.cta} →</a></div></section>
  </main>;
}
